package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Entry Non-Med Date")
	private java.lang.String entryNonMedDate;
	@org.kie.api.definition.type.Label("Intermediate Non-Med Date")
	private java.lang.String intermediateNonMedDate;
	@org.kie.api.definition.type.Label("Supreme Non-Med Date")
	private java.lang.String supremeNonMedDate;
	@org.kie.api.definition.type.Label("UW Dept Remark")
	private java.lang.String uwDeptRemark;

	@org.kie.api.definition.type.Label("Agent Type")
	private java.lang.String agentType;

	@org.kie.api.definition.type.Label(value = "Agent Level")
	private java.lang.String agentLevel;

	public Agent() {
	}

	public java.lang.String getEntryNonMedDate() {
		return this.entryNonMedDate;
	}

	public void setEntryNonMedDate(java.lang.String entryNonMedDate) {
		this.entryNonMedDate = entryNonMedDate;
	}

	public java.lang.String getIntermediateNonMedDate() {
		return this.intermediateNonMedDate;
	}

	public void setIntermediateNonMedDate(
			java.lang.String intermediateNonMedDate) {
		this.intermediateNonMedDate = intermediateNonMedDate;
	}

	public java.lang.String getSupremeNonMedDate() {
		return this.supremeNonMedDate;
	}

	public void setSupremeNonMedDate(java.lang.String supremeNonMedDate) {
		this.supremeNonMedDate = supremeNonMedDate;
	}

	public java.lang.String getUwDeptRemark() {
		return this.uwDeptRemark;
	}

	public void setUwDeptRemark(java.lang.String uwDeptRemark) {
		this.uwDeptRemark = uwDeptRemark;
	}

	public java.lang.String getAgentType() {
		return this.agentType;
	}

	public void setAgentType(java.lang.String agentType) {
		this.agentType = agentType;
	}

	public java.lang.String getAgentLevel() {
		return this.agentLevel;
	}

	public void setAgentLevel(java.lang.String agentLevel) {
		this.agentLevel = agentLevel;
	}

	public Agent(java.lang.String entryNonMedDate,
			java.lang.String intermediateNonMedDate,
			java.lang.String supremeNonMedDate, java.lang.String uwDeptRemark,
			java.lang.String agentType, java.lang.String agentLevel) {
		this.entryNonMedDate = entryNonMedDate;
		this.intermediateNonMedDate = intermediateNonMedDate;
		this.supremeNonMedDate = supremeNonMedDate;
		this.uwDeptRemark = uwDeptRemark;
		this.agentType = agentType;
		this.agentLevel = agentLevel;
	}

}