package com.axa.dm.autouw;

import java.util.List;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationRider implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private static List isActiveList;

	@org.kie.api.definition.type.Label("Rated")
	private boolean rated;

	@org.kie.api.definition.type.Label("Daily Income")
	private java.math.BigDecimal dailyIncome;

	@org.kie.api.definition.type.Label("Fin Limit Multiplier")
	private java.math.BigDecimal finLimitMultiplier;

	@org.kie.api.definition.type.Label("Product Series")
	private java.lang.String productSeries;

	@org.kie.api.definition.type.Label("Product Series High")
	private java.lang.String productSeriesHigh;

	@org.kie.api.definition.type.Label("Product Series Low level")
	private java.lang.String productSeriesLow;

	@org.kie.api.definition.type.Label("Indexation")
	private boolean indexation;

	@org.kie.api.definition.type.Label("productType2")
	private java.lang.String productType2;

	@org.kie.api.definition.type.Label("productType3")
	private java.lang.String productType3;

	@org.kie.api.definition.type.Label("productType4")
	private java.lang.String productType4;

	@org.kie.api.definition.type.Label("Standard Class flag")
	private Boolean standardClass;

	@org.kie.api.definition.type.Label("productSeriesConcat")
	private java.lang.String productSeriesConcat;

	@org.kie.api.definition.type.Label("dateofSubmission")
	private java.lang.String dateofSubmission;

	@org.kie.api.definition.type.Label(value = "Fin Limit of rule 45")
	private java.math.BigDecimal finLimit45;

	static {
		isActiveList = new ArrayList();
		isActiveList.add("00");
		isActiveList.add("01");
		isActiveList.add("02");
		isActiveList.add("04");
		isActiveList.add("05");
		isActiveList.add("06");
		isActiveList.add("07");
	}

	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label("Application No")
	private java.lang.String applicationNo;
	@org.kie.api.definition.type.Label("Sum Insured")
	private java.math.BigDecimal sumInsured;
	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String planCode;
	@org.kie.api.definition.type.Label("Class Code")
	private java.lang.String classCode;
	@org.kie.api.definition.type.Label("Temp Loading")
	private java.math.BigDecimal tempLoading;
	@org.kie.api.definition.type.Label("Loading")
	private java.math.BigDecimal loading;

	@org.kie.api.definition.type.Label("$currency")
	private java.lang.String currency;

	@org.kie.api.definition.type.Label("Sum Insured in HKD")
	private java.math.BigDecimal sumInsuredHkd;

	@org.kie.api.definition.type.Label("Product Group")
	private java.lang.String productGroup;

	@org.kie.api.definition.type.Label("Product Type")
	private java.lang.String productType;

	@org.kie.api.definition.type.Label("Current Role")
	private java.lang.String currentRole;

	@org.kie.api.definition.type.Label("Application Status")
	private java.lang.String applicationStatus;

	public ApplicationRider() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getApplicationNo() {
		return this.applicationNo;
	}

	public void setApplicationNo(java.lang.String applicationNo) {
		this.applicationNo = applicationNo;
	}

	public java.math.BigDecimal getSumInsured() {
		return this.sumInsured;
	}

	public void setSumInsured(java.math.BigDecimal sumInsured) {
		this.sumInsured = sumInsured;
	}

	public java.lang.String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(java.lang.String planCode) {
		this.planCode = planCode;
	}

	public java.lang.String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(java.lang.String classCode) {
		this.classCode = classCode;
	}

	public java.math.BigDecimal getTempLoading() {
		return this.tempLoading;
	}

	public void setTempLoading(java.math.BigDecimal tempLoading) {
		this.tempLoading = tempLoading;
	}

	public java.math.BigDecimal getLoading() {
		return this.loading;
	}

	public void setLoading(java.math.BigDecimal loading) {
		this.loading = loading;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.math.BigDecimal getSumInsuredHkd() {
		return this.sumInsuredHkd;
	}

	public void setSumInsuredHkd(java.math.BigDecimal sumInsuredHkd) {
		this.sumInsuredHkd = sumInsuredHkd;
	}

	public java.lang.String getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(java.lang.String productGroup) {
		this.productGroup = productGroup;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getCurrentRole() {
		return this.currentRole;
	}

	public void setCurrentRole(java.lang.String currentRole) {
		this.currentRole = currentRole;
	}

	public java.lang.String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(java.lang.String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public boolean isActive(String appStatus) {
		if (isActiveList.contains(appStatus))
			return true;
		return false;
	}

	public boolean isRated() {
		return this.rated;
	}

	public void setRated(boolean rated) {
		this.rated = rated;
	}

	public java.math.BigDecimal getDailyIncome() {
		return this.dailyIncome;
	}

	public void setDailyIncome(java.math.BigDecimal dailyIncome) {
		this.dailyIncome = dailyIncome;
	}

	public java.math.BigDecimal getFinLimitMultiplier() {
		return this.finLimitMultiplier;
	}

	public void setFinLimitMultiplier(java.math.BigDecimal finLimitMultiplier) {
		this.finLimitMultiplier = finLimitMultiplier;
	}

	public java.lang.String getProductSeries() {
		return this.productSeries;
	}

	public void setProductSeries(java.lang.String productSeries) {
		this.productSeries = productSeries;
	}

	public java.lang.String getProductSeriesHigh() {
		return this.productSeriesHigh;
	}

	public void setProductSeriesHigh(java.lang.String productSeriesHigh) {
		this.productSeriesHigh = productSeriesHigh;
	}

	public java.lang.String getProductSeriesLow() {
		return this.productSeriesLow;
	}

	public void setProductSeriesLow(java.lang.String productSeriesLow) {
		this.productSeriesLow = productSeriesLow;
	}

	public boolean isIndexation() {
		return this.indexation;
	}

	public void setIndexation(boolean indexation) {
		this.indexation = indexation;
	}

	public java.lang.String getProductType2() {
		return this.productType2;
	}

	public void setProductType2(java.lang.String productType2) {
		this.productType2 = productType2;
	}

	public java.lang.String getProductType3() {
		return this.productType3;
	}

	public void setProductType3(java.lang.String productType3) {
		this.productType3 = productType3;
	}

	public java.lang.String getProductType4() {
		return this.productType4;
	}

	public void setProductType4(java.lang.String productType4) {
		this.productType4 = productType4;
	}

	public boolean isValidProduct(String... strings) {
		for (String s : strings) {
			if (s.equalsIgnoreCase(this.planCode))
				return true;
			if (s.equalsIgnoreCase(this.productType))
				return true;
			if (s.equalsIgnoreCase(this.productSeries))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesHigh))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesLow))
				return true;
		}
		return false;
	}

	public java.lang.Boolean getStandardClass() {
		return this.standardClass;
	}

	public void setStandardClass(java.lang.Boolean standardClass) {
		this.standardClass = standardClass;
	}

	public java.lang.String getProductSeriesConcat() {
		String s = "";
		if (this.productType != null && !"".equals(this.productType))
			s = s + "," + this.productType;

		if (this.productSeries != null && !"".equals(this.productSeries))
			s = s + "," + this.productSeries;

		if (this.productSeriesHigh != null
				&& !"".equals(this.productSeriesHigh))
			s = s + "," + this.productSeriesHigh;

		if (this.productSeriesLow != null && !"".equals(this.productSeriesLow))
			s = s + "," + this.productSeriesLow;

		return ("".equals(s)) ? s : s.substring(1);
	}

	public void setProductSeriesConcat(java.lang.String productSeriesConcat) {
		this.productSeriesConcat = productSeriesConcat;
	}

	public java.lang.String getDateofSubmission() {
		return this.dateofSubmission;
	}

	public void setDateofSubmission(java.lang.String dateofSubmission) {
		this.dateofSubmission = dateofSubmission;
	}

	public java.util.Date getDateofSubmissionCal() {
		try {
			if (this.dateofSubmission != null
					&& !this.dateofSubmission.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.dateofSubmission);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public java.math.BigDecimal getFinLimit45() {
		return this.finLimit45;
	}

	public void setFinLimit45(java.math.BigDecimal finLimit45) {
		this.finLimit45 = finLimit45;
	}

	public ApplicationRider(boolean rated, java.math.BigDecimal dailyIncome,
			java.math.BigDecimal finLimitMultiplier,
			java.lang.String productSeries, java.lang.String productSeriesHigh,
			java.lang.String productSeriesLow, boolean indexation,
			java.lang.String productType2, java.lang.String productType3,
			java.lang.String productType4, java.lang.Boolean standardClass,
			java.lang.String productSeriesConcat,
			java.lang.String dateofSubmission, java.math.BigDecimal finLimit45,
			java.lang.String role, java.lang.String applicationNo,
			java.math.BigDecimal sumInsured, java.lang.String planCode,
			java.lang.String classCode, java.math.BigDecimal tempLoading,
			java.math.BigDecimal loading, java.lang.String currency,
			java.math.BigDecimal sumInsuredHkd, java.lang.String productGroup,
			java.lang.String productType, java.lang.String currentRole,
			java.lang.String applicationStatus) {
		this.rated = rated;
		this.dailyIncome = dailyIncome;
		this.finLimitMultiplier = finLimitMultiplier;
		this.productSeries = productSeries;
		this.productSeriesHigh = productSeriesHigh;
		this.productSeriesLow = productSeriesLow;
		this.indexation = indexation;
		this.productType2 = productType2;
		this.productType3 = productType3;
		this.productType4 = productType4;
		this.standardClass = standardClass;
		this.productSeriesConcat = productSeriesConcat;
		this.dateofSubmission = dateofSubmission;
		this.finLimit45 = finLimit45;
		this.role = role;
		this.applicationNo = applicationNo;
		this.sumInsured = sumInsured;
		this.planCode = planCode;
		this.classCode = classCode;
		this.tempLoading = tempLoading;
		this.loading = loading;
		this.currency = currency;
		this.sumInsuredHkd = sumInsuredHkd;
		this.productGroup = productGroup;
		this.productType = productType;
		this.currentRole = currentRole;
		this.applicationStatus = applicationStatus;
	}

}