package com.axa.dm.autouw;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Basic implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String planCode;
	@org.kie.api.definition.type.Label("Sum Insured")
	private java.math.BigDecimal sumInsured;
	@org.kie.api.definition.type.Label("Max Sum Insured")
	private java.math.BigDecimal maxSumInsured;
	@org.kie.api.definition.type.Label("Min Sum Insured")
	private java.math.BigDecimal minSumInsured;
	@org.kie.api.definition.type.Label("Top-up Premium")
	private java.math.BigDecimal topupPremium;
	@org.kie.api.definition.type.Label("Initial Lump Sum Premium")
	private java.math.BigDecimal initialLumpSumPremium;
	@org.kie.api.definition.type.Label("Modal Regular Premium Exclude Topup")
	private java.math.BigDecimal modalRegularPremiumExcludeTopup;

	@org.kie.api.definition.type.Label("Regular Premium")
	private java.math.BigDecimal regularPremium;

	@org.kie.api.definition.type.Label("Annual Regular Premium")
	private java.math.BigDecimal annualRegularPremium;

	@org.kie.api.definition.type.Label("Product Type")
	private java.lang.String productType;

	@org.kie.api.definition.type.Label("Product Group")
	private java.lang.String productGroup;

	@org.kie.api.definition.type.Label("Sum Insured in HKD")
	private java.math.BigDecimal sumInsuredHkd;

	@org.kie.api.definition.type.Label("Daily Income")
	private java.math.BigDecimal dailyIncome;

	@org.kie.api.definition.type.Label("Fin Limit Multiplier")
	private java.math.BigDecimal finLimitMultiplier;

	@org.kie.api.definition.type.Label("Product Series")
	private java.lang.String productSeries;

	@org.kie.api.definition.type.Label("Product Series High level")
	private java.lang.String productSeriesHigh;

	@org.kie.api.definition.type.Label("Product Series Low level")
	private java.lang.String productSeriesLow;

	@org.kie.api.definition.type.Label("Indexation")
	private boolean indexation;

	@org.kie.api.definition.type.Label("productType2")
	private java.lang.String productType2;

	@org.kie.api.definition.type.Label("productType3")
	private java.lang.String productType3;

	@org.kie.api.definition.type.Label("productType4")
	private java.lang.String productType4;

	@org.kie.api.definition.type.Label("Fin Limit 45")
	private BigDecimal finLimit45;

	public Basic() {
	}

	public java.lang.String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(java.lang.String planCode) {
		this.planCode = planCode;
	}

	public java.math.BigDecimal getSumInsured() {
		return this.sumInsured;
	}

	public void setSumInsured(java.math.BigDecimal sumInsured) {
		this.sumInsured = sumInsured;
	}

	public java.math.BigDecimal getMaxSumInsured() {
		return this.maxSumInsured;
	}

	public void setMaxSumInsured(java.math.BigDecimal maxSumInsured) {
		this.maxSumInsured = maxSumInsured;
	}

	public java.math.BigDecimal getMinSumInsured() {
		return this.minSumInsured;
	}

	public void setMinSumInsured(java.math.BigDecimal minSumInsured) {
		this.minSumInsured = minSumInsured;
	}

	public java.math.BigDecimal getTopupPremium() {
		return this.topupPremium;
	}

	public void setTopupPremium(java.math.BigDecimal topupPremium) {
		this.topupPremium = topupPremium;
	}

	public java.math.BigDecimal getInitialLumpSumPremium() {
		return this.initialLumpSumPremium;
	}

	public void setInitialLumpSumPremium(
			java.math.BigDecimal initialLumpSumPremium) {
		this.initialLumpSumPremium = initialLumpSumPremium;
	}

	public java.math.BigDecimal getModalRegularPremiumExcludeTopup() {
		return this.modalRegularPremiumExcludeTopup;
	}

	public void setModalRegularPremiumExcludeTopup(
			java.math.BigDecimal modalRegularPremiumExcludeTopup) {
		this.modalRegularPremiumExcludeTopup = modalRegularPremiumExcludeTopup;
	}

	public java.math.BigDecimal getRegularPremium() {
		return this.regularPremium;
	}

	public void setRegularPremium(java.math.BigDecimal regularPremium) {
		this.regularPremium = regularPremium;
	}

	public java.math.BigDecimal getAnnualRegularPremium() {
		return this.annualRegularPremium;
	}

	public void setAnnualRegularPremium(
			java.math.BigDecimal annualRegularPremium) {
		this.annualRegularPremium = annualRegularPremium;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(java.lang.String productGroup) {
		this.productGroup = productGroup;
	}

	public java.math.BigDecimal getSumInsuredHkd() {
		return this.sumInsuredHkd;
	}

	public void setSumInsuredHkd(java.math.BigDecimal sumInsuredHkd) {
		this.sumInsuredHkd = sumInsuredHkd;
	}

	public java.math.BigDecimal getDailyIncome() {
		return this.dailyIncome;
	}

	public void setDailyIncome(java.math.BigDecimal dailyIncome) {
		this.dailyIncome = dailyIncome;
	}

	public java.math.BigDecimal getFinLimitMultiplier() {
		return this.finLimitMultiplier;
	}

	public void setFinLimitMultiplier(java.math.BigDecimal finLimitMultiplier) {
		this.finLimitMultiplier = finLimitMultiplier;
	}

	public java.lang.String getProductSeries() {
		return this.productSeries;
	}

	public void setProductSeries(java.lang.String productSeries) {
		this.productSeries = productSeries;
	}

	public java.lang.String getProductSeriesHigh() {
		return this.productSeriesHigh;
	}

	public void setProductSeriesHigh(java.lang.String productSeriesHigh) {
		this.productSeriesHigh = productSeriesHigh;
	}

	public java.lang.String getProductSeriesLow() {
		return this.productSeriesLow;
	}

	public void setProductSeriesLow(java.lang.String productSeriesLow) {
		this.productSeriesLow = productSeriesLow;
	}

	public boolean isIndexation() {
		return this.indexation;
	}

	public void setIndexation(boolean indexation) {
		this.indexation = indexation;
	}

	public java.lang.String getProductType2() {
		return this.productType2;
	}

	public void setProductType2(java.lang.String productType2) {
		this.productType2 = productType2;
	}

	public java.lang.String getProductType3() {
		return this.productType3;
	}

	public void setProductType3(java.lang.String productType3) {
		this.productType3 = productType3;
	}

	public java.lang.String getProductType4() {
		return this.productType4;
	}

	public void setProductType4(java.lang.String productType4) {
		this.productType4 = productType4;
	}

	public boolean isValidProduct(String... strings) {
		for (String s : strings) {
			if (s.equalsIgnoreCase(this.planCode))
				return true;
			if (s.equalsIgnoreCase(this.productType))
				return true;
			if (s.equalsIgnoreCase(this.productSeries))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesHigh))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesLow))
				return true;
		}
		return false;
	}

	public java.math.BigDecimal getFinLimit45() {
		return this.finLimit45;
	}

	public void setFinLimit45(java.math.BigDecimal finLimit45) {
		this.finLimit45 = finLimit45;
	}

	public Basic(java.lang.String planCode, java.math.BigDecimal sumInsured,
			java.math.BigDecimal maxSumInsured,
			java.math.BigDecimal minSumInsured,
			java.math.BigDecimal topupPremium,
			java.math.BigDecimal initialLumpSumPremium,
			java.math.BigDecimal modalRegularPremiumExcludeTopup,
			java.math.BigDecimal regularPremium,
			java.math.BigDecimal annualRegularPremium,
			java.lang.String productType, java.lang.String productGroup,
			java.math.BigDecimal sumInsuredHkd,
			java.math.BigDecimal dailyIncome,
			java.math.BigDecimal finLimitMultiplier,
			java.lang.String productSeries, java.lang.String productSeriesHigh,
			java.lang.String productSeriesLow, boolean indexation,
			java.lang.String productType2, java.lang.String productType3,
			java.lang.String productType4, java.math.BigDecimal finLimit45) {
		this.planCode = planCode;
		this.sumInsured = sumInsured;
		this.maxSumInsured = maxSumInsured;
		this.minSumInsured = minSumInsured;
		this.topupPremium = topupPremium;
		this.initialLumpSumPremium = initialLumpSumPremium;
		this.modalRegularPremiumExcludeTopup = modalRegularPremiumExcludeTopup;
		this.regularPremium = regularPremium;
		this.annualRegularPremium = annualRegularPremium;
		this.productType = productType;
		this.productGroup = productGroup;
		this.sumInsuredHkd = sumInsuredHkd;
		this.dailyIncome = dailyIncome;
		this.finLimitMultiplier = finLimitMultiplier;
		this.productSeries = productSeries;
		this.productSeriesHigh = productSeriesHigh;
		this.productSeriesLow = productSeriesLow;
		this.indexation = indexation;
		this.productType2 = productType2;
		this.productType3 = productType3;
		this.productType4 = productType4;
		this.finLimit45 = finLimit45;
	}

}