package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Beneficiary implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Beneficiary Name")
	private java.lang.String beneficiaryName;
	@org.kie.api.definition.type.Label(value = "Beneficiary Relationship")
	private java.lang.String beneficiaryRelationship;

	public Beneficiary() {
	}

	public java.lang.String getBeneficiaryName() {
		return this.beneficiaryName;
	}

	public void setBeneficiaryName(java.lang.String beneficiaryName) {
		this.beneficiaryName = beneficiaryName;
	}

	public java.lang.String getBeneficiaryRelationship() {
		return this.beneficiaryRelationship;
	}

	public void setBeneficiaryRelationship(
			java.lang.String beneficiaryRelationship) {
		this.beneficiaryRelationship = beneficiaryRelationship;
	}

	public Beneficiary(java.lang.String beneficiaryName,
			java.lang.String beneficiaryRelationship) {
		this.beneficiaryName = beneficiaryName;
		this.beneficiaryRelationship = beneficiaryRelationship;
	}

}