package com.axa.dm.autouw;

import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label("Policy No")
	private java.lang.String policyNo;
	@org.kie.api.definition.type.Label("Claim Type")
	private java.lang.String claimType;
	@org.kie.api.definition.type.Label("Incident Date")
	private java.lang.String incidentDate;
	@org.kie.api.definition.type.Label("Claim Period To")
	private java.lang.String claimPeriodTo;
	@org.kie.api.definition.type.Label("Claim Period From")
	private java.lang.String claimPeriodFrom;

	@org.kie.api.definition.type.Label("Claim Status")
	private java.lang.String claimStatus;

	@org.kie.api.definition.type.Label("Claim Number")
	private java.lang.String claimNumber;

	@org.kie.api.definition.type.Label("Days of Discharge")
	private java.lang.String daysofDischarge;

	@org.kie.api.definition.type.Label("Days of Admission")
	private java.lang.String daysofAdmission;

	@org.kie.api.definition.type.Label("diagnostic code")
	private java.lang.String diagnosticcode;

	@org.kie.api.definition.type.Label("surgical codes")
	private java.lang.String surgicalcodes;

	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String plancode;

	@org.kie.api.definition.type.Label("Is Diagnostic & surgical code in list?")
	private boolean codeInList;

	@org.kie.api.definition.type.Label("Claim Period From for calculation")
	private java.util.Date claimPeriodFromCal;

	@org.kie.api.definition.type.Label("Claim Period To for calculation")
	private java.util.Date claimPeriodToCal;

	@org.kie.api.definition.type.Label("Days of Admission for calculation")
	private java.util.Date daysofAdmissionCal;

	@org.kie.api.definition.type.Label("Days of Discharge for calculation")
	private java.util.Date daysofDischargeCal;

	@org.kie.api.definition.type.Label("Product Type")
	private java.lang.String productType;

	@org.kie.api.definition.type.Label("Current Role")
	private java.lang.String currentRole;

	@org.kie.api.definition.type.Label("Product Series")
	private java.lang.String productSeries;

	@org.kie.api.definition.type.Label("Product Series High level")
	private java.lang.String productSeriesHigh;

	@org.kie.api.definition.type.Label("Product Series Low level")
	private java.lang.String productSeriesLow;

	@org.kie.api.definition.type.Label(value = "Diagnostic Code in List?")
	private boolean diagnosticCodeInList;

	@org.kie.api.definition.type.Label(value = "Surgical Code in List?")
	private boolean surgicalCodeInList;

	public Claim() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(java.lang.String claimType) {
		this.claimType = claimType;
	}

	public java.lang.String getIncidentDate() {
		return this.incidentDate;
	}

	public java.util.Date getIncidentDateCal() {
		try {
			if (this.incidentDate != null && !this.incidentDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.incidentDate);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			e.printStackTrace();
			return null;
		}
	}

	public void setIncidentDate(java.lang.String incidentDate) {
		this.incidentDate = incidentDate;
	}

	public java.lang.String getClaimPeriodTo() {
		return this.claimPeriodTo;
	}

	public java.util.Date getClaimPeriodToCal() {
		try {
			if (this.claimPeriodTo != null && !this.claimPeriodTo.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.claimPeriodTo);
				return newDate;
			}

			return null;

		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public void setClaimPeriodTo(java.lang.String claimPeriodTo) {
		this.claimPeriodTo = claimPeriodTo;
	}

	public java.lang.String getClaimPeriodFrom() {
		return this.claimPeriodFrom;
	}

	public java.util.Date getClaimPeriodFromCal() {
		try {

			if (this.claimPeriodFrom != null && !this.claimPeriodFrom.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.claimPeriodFrom);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public void setClaimPeriodFrom(java.lang.String claimPeriodFrom) {
		this.claimPeriodFrom = claimPeriodFrom;
	}

	public java.lang.String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(java.lang.String claimStatus) {
		this.claimStatus = claimStatus;
	}

	public java.lang.String getClaimNumber() {
		return this.claimNumber;
	}

	public void setClaimNumber(java.lang.String claimNumber) {
		this.claimNumber = claimNumber;
	}

	public java.lang.String getDaysofDischarge() {
		return this.daysofDischarge;
	}

	public java.util.Date getDaysofDischargeCal() {
		try {
			if (this.daysofDischarge != null && !this.daysofDischarge.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.daysofDischarge);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public void setDaysofDischarge(java.lang.String daysofDischarge) {
		this.daysofDischarge = daysofDischarge;
	}

	public java.lang.String getDaysofAdmission() {
		return this.daysofAdmission;
	}

	public java.util.Date getDaysofAdmissionCal() {
		try {
			if (this.daysofAdmission != null && !this.daysofAdmission.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.daysofAdmission);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public void setDaysofAdmission(java.lang.String daysofAdmission) {
		this.daysofAdmission = daysofAdmission;
	}

	public java.lang.String getDiagnosticcode() {
		return this.diagnosticcode;
	}

	public void setDiagnosticcode(java.lang.String diagnosticcode) {
		this.diagnosticcode = diagnosticcode;
	}

	public java.lang.String getSurgicalcodes() {
		return this.surgicalcodes;
	}

	public void setSurgicalcodes(java.lang.String surgicalcodes) {
		this.surgicalcodes = surgicalcodes;
	}

	public java.lang.String getPlancode() {
		return this.plancode;
	}

	public void setPlancode(java.lang.String plancode) {
		this.plancode = plancode;
	}

	public boolean isCodeInList() {
		return this.codeInList;
	}

	public void setCodeInList(boolean codeInList) {
		this.codeInList = codeInList;
	}

	public void setClaimPeriodFromCal(java.util.Date claimPeriodFromCal) {
		this.claimPeriodFromCal = claimPeriodFromCal;
	}

	public void setClaimPeriodToCal(java.util.Date claimPeriodToCal) {
		this.claimPeriodToCal = claimPeriodToCal;
	}

	public void setDaysofAdmissionCal(java.util.Date daysofAdmissionCal) {
		this.daysofAdmissionCal = daysofAdmissionCal;
	}

	public void setDaysofDischargeCal(java.util.Date daysofDischargeCal) {
		this.daysofDischargeCal = daysofDischargeCal;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getCurrentRole() {
		return this.currentRole;
	}

	public void setCurrentRole(java.lang.String currentRole) {
		this.currentRole = currentRole;
	}

	public java.lang.String getProductSeries() {
		return this.productSeries;
	}

	public void setProductSeries(java.lang.String productSeries) {
		this.productSeries = productSeries;
	}

	public java.lang.String getProductSeriesHigh() {
		return this.productSeriesHigh;
	}

	public void setProductSeriesHigh(java.lang.String productSeriesHigh) {
		this.productSeriesHigh = productSeriesHigh;
	}

	public java.lang.String getProductSeriesLow() {
		return this.productSeriesLow;
	}

	public void setProductSeriesLow(java.lang.String productSeriesLow) {
		this.productSeriesLow = productSeriesLow;
	}

	public boolean isValidProduct(String... strings) {
		for (String s : strings) {
			if (s.equals(this.plancode))
				return true;
			if (s.equals(this.productType))
				return true;
			if (s.equals(this.productSeries))
				return true;
			if (s.equals(this.productSeriesHigh))
				return true;
			if (s.equals(this.productSeriesLow))
				return true;
		}
		return false;
	}

	public boolean isDiagnosticCodeInList() {
		return this.diagnosticCodeInList;
	}

	public void setDiagnosticCodeInList(boolean diagnosticCodeInList) {
		this.diagnosticCodeInList = diagnosticCodeInList;
	}

	public boolean isSurgicalCodeInList() {
		return this.surgicalCodeInList;
	}

	public void setSurgicalCodeInList(boolean surgicalCodeInList) {
		this.surgicalCodeInList = surgicalCodeInList;
	}

	public Claim(java.lang.String role, java.lang.String policyNo,
			java.lang.String claimType, java.lang.String incidentDate,
			java.lang.String claimPeriodTo, java.lang.String claimPeriodFrom,
			java.lang.String claimStatus, java.lang.String claimNumber,
			java.lang.String daysofDischarge, java.lang.String daysofAdmission,
			java.lang.String diagnosticcode, java.lang.String surgicalcodes,
			java.lang.String plancode, boolean codeInList,
			java.util.Date claimPeriodFromCal, java.util.Date claimPeriodToCal,
			java.util.Date daysofAdmissionCal,
			java.util.Date daysofDischargeCal, java.lang.String productType,
			java.lang.String currentRole, java.lang.String productSeries,
			java.lang.String productSeriesHigh,
			java.lang.String productSeriesLow, boolean diagnosticCodeInList,
			boolean surgicalCodeInList) {
		this.role = role;
		this.policyNo = policyNo;
		this.claimType = claimType;
		this.incidentDate = incidentDate;
		this.claimPeriodTo = claimPeriodTo;
		this.claimPeriodFrom = claimPeriodFrom;
		this.claimStatus = claimStatus;
		this.claimNumber = claimNumber;
		this.daysofDischarge = daysofDischarge;
		this.daysofAdmission = daysofAdmission;
		this.diagnosticcode = diagnosticcode;
		this.surgicalcodes = surgicalcodes;
		this.plancode = plancode;
		this.codeInList = codeInList;
		this.claimPeriodFromCal = claimPeriodFromCal;
		this.claimPeriodToCal = claimPeriodToCal;
		this.daysofAdmissionCal = daysofAdmissionCal;
		this.daysofDischargeCal = daysofDischargeCal;
		this.productType = productType;
		this.currentRole = currentRole;
		this.productSeries = productSeries;
		this.productSeriesHigh = productSeriesHigh;
		this.productSeriesLow = productSeriesLow;
		this.diagnosticCodeInList = diagnosticCodeInList;
		this.surgicalCodeInList = surgicalCodeInList;
	}

}