package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constants implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public static final String failDecision = "Fail";
    public static final String decimalFormatString = "#,###";
    public static final String ownerPayorId = "O";
    public static final String insuredPayorId = "I";
    public static final String insured = "INS";
    public static final String owner = "OWN";

    public Constants() {
    }




}