package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DiagnosticSurgicalObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Code")
	private java.lang.String code;

	public DiagnosticSurgicalObject() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public DiagnosticSurgicalObject(java.lang.String code) {
		this.code = code;
	}

}