package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeRateObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("From Currency")
	private java.lang.String fromCurrency;
	@org.kie.api.definition.type.Label("To Currency")
	private java.lang.String toCurrency;
	@org.kie.api.definition.type.Label("Exchange Rate")
	private java.math.BigDecimal exchangeRate;

	@org.kie.api.definition.type.Label(value = "From Currency Weight")
	private java.math.BigDecimal fromCurrencyWeight;

	@org.kie.api.definition.type.Label(value = "To Currency Weight")
	private java.math.BigDecimal toCurrencyWeight;

	public ExchangeRateObject() {
	}

	public java.lang.String getFromCurrency() {
		return this.fromCurrency;
	}

	public void setFromCurrency(java.lang.String fromCurrency) {
		this.fromCurrency = fromCurrency;
	}

	public java.lang.String getToCurrency() {
		return this.toCurrency;
	}

	public void setToCurrency(java.lang.String toCurrency) {
		this.toCurrency = toCurrency;
	}

	public java.math.BigDecimal getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(java.math.BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public java.math.BigDecimal getFromCurrencyWeight() {
		return this.fromCurrencyWeight;
	}

	public void setFromCurrencyWeight(java.math.BigDecimal fromCurrencyWeight) {
		this.fromCurrencyWeight = fromCurrencyWeight;
	}

	public java.math.BigDecimal getToCurrencyWeight() {
		return this.toCurrencyWeight;
	}

	public void setToCurrencyWeight(java.math.BigDecimal toCurrencyWeight) {
		this.toCurrencyWeight = toCurrencyWeight;
	}

	public ExchangeRateObject(java.lang.String fromCurrency,
			java.lang.String toCurrency, java.math.BigDecimal exchangeRate,
			java.math.BigDecimal fromCurrencyWeight,
			java.math.BigDecimal toCurrencyWeight) {
		this.fromCurrency = fromCurrency;
		this.toCurrency = toCurrency;
		this.exchangeRate = exchangeRate;
		this.fromCurrencyWeight = fromCurrencyWeight;
		this.toCurrencyWeight = toCurrencyWeight;
	}

}