package com.axa.dm.autouw;

import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IndividualResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Rule No")
	private java.lang.String ruleNo;
	@org.kie.api.definition.type.Label("Decision")
	private java.lang.String decision;
	@org.kie.api.definition.type.Label("Message to Client English")
	private java.lang.String messageToClientEng;
	@org.kie.api.definition.type.Label("Message to Client Chinese")
	private java.lang.String messageToClientChi;
	@org.kie.api.definition.type.Label("Owner Individual")
	private com.axa.dm.autouw.OwnerIndividual ownerIndividual;

	@org.kie.api.definition.type.Label("Insured Individual")
	private com.axa.dm.autouw.InsuredIndividual insuredIndividual;

	@org.kie.api.definition.type.Label("Rule Name")
	private java.lang.String ruleName;

	public IndividualResult() {
	}

	public java.lang.String getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(java.lang.String ruleNo) {
		this.ruleNo = ruleNo;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public java.lang.String getMessageToClientEng() {
		return this.messageToClientEng;
	}

	public void setMessageToClientEng(java.lang.String messageToClientEng) {
		this.messageToClientEng = messageToClientEng;
	}

	public java.lang.String getMessageToClientChi() {
		return this.messageToClientChi;
	}

	public void setMessageToClientChi(java.lang.String messageToClientChi) {
		this.messageToClientChi = messageToClientChi;
	}

	public com.axa.dm.autouw.OwnerIndividual getOwnerIndividual() {
		return this.ownerIndividual;
	}

	public void setOwnerIndividual(
			com.axa.dm.autouw.OwnerIndividual ownerIndividual) {
		this.ownerIndividual = ownerIndividual;
	}

	public com.axa.dm.autouw.InsuredIndividual getInsuredIndividual() {
		return this.insuredIndividual;
	}

	public void setInsuredIndividual(
			com.axa.dm.autouw.InsuredIndividual insuredIndividual) {
		this.insuredIndividual = insuredIndividual;
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}
	
	public String toJson(){
	    ObjectMapper mapper = new ObjectMapper();
	    try {
	        String jsonInString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(this);
	        return jsonInString;
	    } catch (JsonGenerationException e) {
			e.printStackTrace();
			return null;
		} catch (JsonMappingException e) {
			e.printStackTrace();
			return null;
		} catch (IOException e) {
			e.printStackTrace();
			return null;
		}
    }

	public IndividualResult(java.lang.String ruleNo, java.lang.String decision,
			java.lang.String messageToClientEng,
			java.lang.String messageToClientChi,
			com.axa.dm.autouw.OwnerIndividual ownerIndividual,
			com.axa.dm.autouw.InsuredIndividual insuredIndividual,
			java.lang.String ruleName) {
		this.ruleNo = ruleNo;
		this.decision = decision;
		this.messageToClientEng = messageToClientEng;
		this.messageToClientChi = messageToClientChi;
		this.ownerIndividual = ownerIndividual;
		this.insuredIndividual = insuredIndividual;
		this.ruleName = ruleName;
	}

}