package com.axa.dm.autouw;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Insured implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Full Name")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label("Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label("ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Nationality")
	private java.lang.String nationality;
	@org.kie.api.definition.type.Label("Country of Residency")
	private java.lang.String countryofResidency;
	@org.kie.api.definition.type.Label("Country of Permanent Address")
	private java.lang.String countryofPermanentAddress;
	@org.kie.api.definition.type.Label("Country of Residency 6 Months")
	private java.lang.String countryofResidency6Months;
	@org.kie.api.definition.type.Label("Tax Residency")
	private boolean taxResidency;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("DOB")
	private java.lang.String dob;
	@org.kie.api.definition.type.Label("Replace of Policy Option")
	private boolean replaceofPolicyOption;
	@org.kie.api.definition.type.Label("Occupation Class")
	private java.lang.String occupationClass;
	@org.kie.api.definition.type.Label("Occupation Name")
	private java.lang.String occupationName;
	@org.kie.api.definition.type.Label("Company Name")
	private java.lang.String companyName;
	@org.kie.api.definition.type.Label("National Holding Flag")
	private boolean nationalHoldingFlag;

	@org.kie.api.definition.type.Label("Monthly Income")
	private java.math.BigDecimal monthlyIncomeApp;

	@org.kie.api.definition.type.Label("Disposable Monthly Income")
	private java.math.BigDecimal monthlyIncome;

	@org.kie.api.definition.type.Label("Monthly Expense")
	private java.math.BigDecimal monthlyExpense;

	@org.kie.api.definition.type.Label("Occupation Description")
	private java.lang.String occupationDesc;

	@org.kie.api.definition.type.Label("Income Multiplier")
	private java.math.BigDecimal incomeMultiplier;

	@org.kie.api.definition.type.Label("Annual Income")
	private java.math.BigDecimal annualIncome;

	@org.kie.api.definition.type.Label("Annual Income ECNA")
	private java.math.BigDecimal annualIncomeEcna;

	@org.kie.api.definition.type.Label("Annual Expense")
	private java.math.BigDecimal annualExpense;

	@org.kie.api.definition.type.Label("Annual Disposable Income")
	private java.math.BigDecimal annualDisposableIncome;

	@org.kie.api.definition.type.Label("occupationRiskFlag")
	private boolean occupationRiskFlag;

	@org.kie.api.definition.type.Label("Max Life Sum Insured in HKD")
	private java.math.BigDecimal maxLifeSumInsuredHkd;

	@org.kie.api.definition.type.Label("Max Life Sum Insured in USD")
	private java.math.BigDecimal maxLifeSumInsuredUsd;

	@org.kie.api.definition.type.Label("Residency massaged")
	private java.lang.String residencyCal;

	@org.kie.api.definition.type.Label("Term Basic Max Life Sum Insured in HKD")
	private java.math.BigDecimal termBasicMaxSiHkd;

	@org.kie.api.definition.type.Label("Basic Max Life Sum Insured in USD")
	private java.math.BigDecimal termBasicMaxSiUsd;

	@org.kie.api.definition.type.Label("Term Rider Max Life Sum Insured in HKD")
	private java.math.BigDecimal termRiderMaxSiHkd;

	@org.kie.api.definition.type.Label("Term Rider Max Life Sum Insured in USD")
	private java.math.BigDecimal termRiderMaxSiUsd;

	@org.kie.api.definition.type.Label("ES Rider Max Sum Insured in HKD")
	private java.math.BigDecimal esRiderMaxSiHkd;

	@org.kie.api.definition.type.Label("ES Rider Max Sum Insured in USD")
	private java.math.BigDecimal esRiderMaxSiUsd;

	@org.kie.api.definition.type.Label("LIP / SLI Max Sum Insured in HKD")
	private java.math.BigDecimal lipMaxSiHkd;

	@org.kie.api.definition.type.Label("LIP Max Sum Insured in USD")
	private java.math.BigDecimal lipMaxSiUsd;

	@org.kie.api.definition.type.Label("CI of AIO Max Sum Insured in HKD")
	private java.math.BigDecimal ciAioMaxSiHkd;

	@org.kie.api.definition.type.Label("CI of AIO Max Sum Insured in USD")
	private java.math.BigDecimal ciAioMaxSiUsd;

	@org.kie.api.definition.type.Label("ELI Max Sum Insured in HKD")
	private java.math.BigDecimal eliMaxSiHkd;

	@org.kie.api.definition.type.Label("ELI Max Sum Insured in USD")
	private java.math.BigDecimal eliMaxSiUsd;

	@org.kie.api.definition.type.Label("ADD Max Sum Insured include ECARE?")
	private boolean addMaxSiWithEcare;

	@org.kie.api.definition.type.Label("ADD Max Sum Insured in HKD")
	private java.math.BigDecimal addMaxSiWithEcareHkd;

	@org.kie.api.definition.type.Label("ADD Max Sum Insured in USD")
	private java.math.BigDecimal addMaxSiWithEcareUsd;

	@org.kie.api.definition.type.Label("Non-Med Life Sum Insured in HKD")
	private java.math.BigDecimal nonMedLifeSiHkd;

	@org.kie.api.definition.type.Label("Non-Med Life Sum Insured in USD")
	private java.math.BigDecimal nonMedLifeSiUsd;

	@org.kie.api.definition.type.Label(value = "CI Max Sum Insured for HA/HB in HKD")
	private java.math.BigDecimal ciHaHbMaxSiHkd;

	@org.kie.api.definition.type.Label(value = "CI Max Sum Insured for HA/HB in USD")
	private java.math.BigDecimal ciHaHbMaxSiUsd;

	@org.kie.api.definition.type.Label(value = "CI Max Sum Inusred for others in HKD")
	private java.math.BigDecimal ciOthersMaxSiHkd;

	@org.kie.api.definition.type.Label(value = "CI Max Sum Insured for others in USD")
	private java.math.BigDecimal ciOthersMaxSiUsd;

	public Insured() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.String getCountryofResidency() {
		return this.countryofResidency;
	}

	public void setCountryofResidency(java.lang.String countryofResidency) {
		this.countryofResidency = countryofResidency;
	}

	public java.lang.String getCountryofPermanentAddress() {
		return this.countryofPermanentAddress;
	}

	public void setCountryofPermanentAddress(
			java.lang.String countryofPermanentAddress) {
		this.countryofPermanentAddress = countryofPermanentAddress;
	}

	public java.lang.String getCountryofResidency6Months() {
		return this.countryofResidency6Months;
	}

	public void setCountryofResidency6Months(
			java.lang.String countryofResidency6Months) {
		this.countryofResidency6Months = countryofResidency6Months;
	}

	public boolean isTaxResidency() {
		return this.taxResidency;
	}

	public void setTaxResidency(boolean taxResidency) {
		this.taxResidency = taxResidency;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getDob() {
		return this.dob;
	}

	public java.util.Date getDobCal() {
		try {
			java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
					.parse(this.dob);
			return newDate;
		} catch (ParseException e) {
			e.printStackTrace();
			return null;
		}
	}

	public void setDob(java.lang.String dob) {
		this.dob = dob;
	}

	public boolean isReplaceofPolicyOption() {
		return this.replaceofPolicyOption;
	}

	public void setReplaceofPolicyOption(boolean replaceofPolicyOption) {
		this.replaceofPolicyOption = replaceofPolicyOption;
	}

	public java.lang.String getOccupationClass() {
		return this.occupationClass;
	}

	public void setOccupationClass(java.lang.String occupationClass) {
		this.occupationClass = occupationClass;
	}

	public java.lang.String getOccupationName() {
		return this.occupationName;
	}

	public void setOccupationName(java.lang.String occupationName) {
		this.occupationName = occupationName;
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public boolean isNationalHoldingFlag() {
		return this.nationalHoldingFlag;
	}

	public void setNationalHoldingFlag(boolean nationalHoldingFlag) {
		this.nationalHoldingFlag = nationalHoldingFlag;
	}

	public java.math.BigDecimal getMonthlyIncomeApp() {
		return this.monthlyIncomeApp;
	}

	public void setMonthlyIncomeApp(java.math.BigDecimal monthlyIncomeApp) {
		this.monthlyIncomeApp = monthlyIncomeApp;
	}

	public java.math.BigDecimal getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.math.BigDecimal monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.math.BigDecimal getMonthlyExpense() {
		return this.monthlyExpense;
	}

	public void setMonthlyExpense(java.math.BigDecimal monthlyExpense) {
		this.monthlyExpense = monthlyExpense;
	}

	public java.lang.String getOccupationDesc() {
		return this.occupationDesc;
	}

	public void setOccupationDesc(java.lang.String occupationDesc) {
		this.occupationDesc = occupationDesc;
	}

	public java.math.BigDecimal getIncomeMultiplier() {
		return this.incomeMultiplier;
	}

	public void setIncomeMultiplier(java.math.BigDecimal incomeMultiplier) {
		this.incomeMultiplier = incomeMultiplier;
	}

	public java.math.BigDecimal getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(java.math.BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	public java.math.BigDecimal getAnnualIncomeEcna() {
		return this.annualIncomeEcna;
	}

	public void setAnnualIncomeEcna(java.math.BigDecimal annualIncomeEcna) {
		this.annualIncomeEcna = annualIncomeEcna;
	}

	public java.math.BigDecimal getAnnualExpense() {
		return this.annualExpense;
	}

	public void setAnnualExpense(java.math.BigDecimal annualExpense) {
		this.annualExpense = annualExpense;
	}

	public java.math.BigDecimal getAnnualDisposableIncome() {
		return this.annualDisposableIncome;
	}

	public void setAnnualDisposableIncome(
			java.math.BigDecimal annualDisposableIncome) {
		this.annualDisposableIncome = annualDisposableIncome;
	}

	public boolean isOccupationRiskFlag() {
		return this.occupationRiskFlag;
	}

	public void setOccupationRiskFlag(boolean occupationRiskFlag) {
		this.occupationRiskFlag = occupationRiskFlag;
	}

	public java.math.BigDecimal getMaxLifeSumInsuredHkd() {
		return this.maxLifeSumInsuredHkd;
	}

	public void setMaxLifeSumInsuredHkd(
			java.math.BigDecimal maxLifeSumInsuredHkd) {
		this.maxLifeSumInsuredHkd = maxLifeSumInsuredHkd;
	}

	public java.math.BigDecimal getMaxLifeSumInsuredUsd() {
		return this.maxLifeSumInsuredUsd;
	}

	public void setMaxLifeSumInsuredUsd(
			java.math.BigDecimal maxLifeSumInsuredUsd) {
		this.maxLifeSumInsuredUsd = maxLifeSumInsuredUsd;
	}

	public java.lang.String getResidencyCal() {
		return this.residencyCal;
	}

	public void setResidencyCal(java.lang.String residencyCal) {
		this.residencyCal = residencyCal;
	}

	public java.math.BigDecimal getTermBasicMaxSiHkd() {
		return this.termBasicMaxSiHkd;
	}

	public void setTermBasicMaxSiHkd(java.math.BigDecimal termBasicMaxSiHkd) {
		this.termBasicMaxSiHkd = termBasicMaxSiHkd;
	}

	public java.math.BigDecimal getTermBasicMaxSiUsd() {
		return this.termBasicMaxSiUsd;
	}

	public void setTermBasicMaxSiUsd(java.math.BigDecimal termBasicMaxSiUsd) {
		this.termBasicMaxSiUsd = termBasicMaxSiUsd;
	}

	public java.math.BigDecimal getTermRiderMaxSiHkd() {
		return this.termRiderMaxSiHkd;
	}

	public void setTermRiderMaxSiHkd(java.math.BigDecimal termRiderMaxSiHkd) {
		this.termRiderMaxSiHkd = termRiderMaxSiHkd;
	}

	public java.math.BigDecimal getTermRiderMaxSiUsd() {
		return this.termRiderMaxSiUsd;
	}

	public void setTermRiderMaxSiUsd(java.math.BigDecimal termRiderMaxSiUsd) {
		this.termRiderMaxSiUsd = termRiderMaxSiUsd;
	}

	public java.math.BigDecimal getEsRiderMaxSiHkd() {
		return this.esRiderMaxSiHkd;
	}

	public void setEsRiderMaxSiHkd(java.math.BigDecimal esRiderMaxSiHkd) {
		this.esRiderMaxSiHkd = esRiderMaxSiHkd;
	}

	public java.math.BigDecimal getEsRiderMaxSiUsd() {
		return this.esRiderMaxSiUsd;
	}

	public void setEsRiderMaxSiUsd(java.math.BigDecimal esRiderMaxSiUsd) {
		this.esRiderMaxSiUsd = esRiderMaxSiUsd;
	}

	public java.math.BigDecimal getLipMaxSiHkd() {
		return this.lipMaxSiHkd;
	}

	public void setLipMaxSiHkd(java.math.BigDecimal lipMaxSiHkd) {
		this.lipMaxSiHkd = lipMaxSiHkd;
	}

	public java.math.BigDecimal getLipMaxSiUsd() {
		return this.lipMaxSiUsd;
	}

	public void setLipMaxSiUsd(java.math.BigDecimal lipMaxSiUsd) {
		this.lipMaxSiUsd = lipMaxSiUsd;
	}

	public java.math.BigDecimal getCiAioMaxSiHkd() {
		return this.ciAioMaxSiHkd;
	}

	public void setCiAioMaxSiHkd(java.math.BigDecimal ciAioMaxSiHkd) {
		this.ciAioMaxSiHkd = ciAioMaxSiHkd;
	}

	public java.math.BigDecimal getCiAioMaxSiUsd() {
		return this.ciAioMaxSiUsd;
	}

	public void setCiAioMaxSiUsd(java.math.BigDecimal ciAioMaxSiUsd) {
		this.ciAioMaxSiUsd = ciAioMaxSiUsd;
	}

	

	public java.math.BigDecimal getEliMaxSiHkd() {
		return this.eliMaxSiHkd;
	}

	public void setEliMaxSiHkd(java.math.BigDecimal eliMaxSiHkd) {
		this.eliMaxSiHkd = eliMaxSiHkd;
	}

	public java.math.BigDecimal getEliMaxSiUsd() {
		return this.eliMaxSiUsd;
	}

	public void setEliMaxSiUsd(java.math.BigDecimal eliMaxSiUsd) {
		this.eliMaxSiUsd = eliMaxSiUsd;
	}

	public boolean isAddMaxSiWithEcare() {
		return this.addMaxSiWithEcare;
	}

	public void setAddMaxSiWithEcare(boolean addMaxSiWithEcare) {
		this.addMaxSiWithEcare = addMaxSiWithEcare;
	}

	public java.math.BigDecimal getAddMaxSiWithEcareHkd() {
		return this.addMaxSiWithEcareHkd;
	}

	public void setAddMaxSiWithEcareHkd(
			java.math.BigDecimal addMaxSiWithEcareHkd) {
		this.addMaxSiWithEcareHkd = addMaxSiWithEcareHkd;
	}

	public java.math.BigDecimal getAddMaxSiWithEcareUsd() {
		return this.addMaxSiWithEcareUsd;
	}

	public void setAddMaxSiWithEcareUsd(
			java.math.BigDecimal addMaxSiWithEcareUsd) {
		this.addMaxSiWithEcareUsd = addMaxSiWithEcareUsd;
	}

	public java.math.BigDecimal getNonMedLifeSiHkd() {
		return this.nonMedLifeSiHkd;
	}

	public void setNonMedLifeSiHkd(java.math.BigDecimal nonMedLifeSiHkd) {
		this.nonMedLifeSiHkd = nonMedLifeSiHkd;
	}

	public java.math.BigDecimal getNonMedLifeSiUsd() {
		return this.nonMedLifeSiUsd;
	}

	public void setNonMedLifeSiUsd(java.math.BigDecimal nonMedLifeSiUsd) {
		this.nonMedLifeSiUsd = nonMedLifeSiUsd;
	}

	public java.math.BigDecimal getCiHaHbMaxSiHkd() {
		return this.ciHaHbMaxSiHkd;
	}

	public void setCiHaHbMaxSiHkd(java.math.BigDecimal ciHaHbMaxSiHkd) {
		this.ciHaHbMaxSiHkd = ciHaHbMaxSiHkd;
	}

	public java.math.BigDecimal getCiHaHbMaxSiUsd() {
		return this.ciHaHbMaxSiUsd;
	}

	public void setCiHaHbMaxSiUsd(java.math.BigDecimal ciHaHbMaxSiUsd) {
		this.ciHaHbMaxSiUsd = ciHaHbMaxSiUsd;
	}

	public java.math.BigDecimal getCiOthersMaxSiHkd() {
		return this.ciOthersMaxSiHkd;
	}

	public void setCiOthersMaxSiHkd(java.math.BigDecimal ciOthersMaxSiHkd) {
		this.ciOthersMaxSiHkd = ciOthersMaxSiHkd;
	}

	public java.math.BigDecimal getCiOthersMaxSiUsd() {
		return this.ciOthersMaxSiUsd;
	}

	public void setCiOthersMaxSiUsd(java.math.BigDecimal ciOthersMaxSiUsd) {
		this.ciOthersMaxSiUsd = ciOthersMaxSiUsd;
	}

	public Insured(java.lang.String fullName, java.lang.String gender,
			java.lang.String id, java.lang.String nationality,
			java.lang.String countryofResidency,
			java.lang.String countryofPermanentAddress,
			java.lang.String countryofResidency6Months, boolean taxResidency,
			java.lang.Integer age, java.lang.String dob,
			boolean replaceofPolicyOption, java.lang.String occupationClass,
			java.lang.String occupationName, java.lang.String companyName,
			boolean nationalHoldingFlag, java.math.BigDecimal monthlyIncomeApp,
			java.math.BigDecimal monthlyIncome,
			java.math.BigDecimal monthlyExpense,
			java.lang.String occupationDesc,
			java.math.BigDecimal incomeMultiplier,
			java.math.BigDecimal annualIncome,
			java.math.BigDecimal annualIncomeEcna,
			java.math.BigDecimal annualExpense,
			java.math.BigDecimal annualDisposableIncome,
			boolean occupationRiskFlag,
			java.math.BigDecimal maxLifeSumInsuredHkd,
			java.math.BigDecimal maxLifeSumInsuredUsd,
			java.lang.String residencyCal,
			java.math.BigDecimal termBasicMaxSiHkd,
			java.math.BigDecimal termBasicMaxSiUsd,
			java.math.BigDecimal termRiderMaxSiHkd,
			java.math.BigDecimal termRiderMaxSiUsd,
			java.math.BigDecimal esRiderMaxSiHkd,
			java.math.BigDecimal esRiderMaxSiUsd,
			java.math.BigDecimal lipMaxSiHkd, java.math.BigDecimal lipMaxSiUsd,
			java.math.BigDecimal ciAioMaxSiHkd,
			java.math.BigDecimal ciAioMaxSiUsd,
			java.math.BigDecimal eliMaxSiHkd, java.math.BigDecimal eliMaxSiUsd,
			boolean addMaxSiWithEcare,
			java.math.BigDecimal addMaxSiWithEcareHkd,
			java.math.BigDecimal addMaxSiWithEcareUsd,
			java.math.BigDecimal nonMedLifeSiHkd,
			java.math.BigDecimal nonMedLifeSiUsd,
			java.math.BigDecimal ciHaHbMaxSiHkd,
			java.math.BigDecimal ciHaHbMaxSiUsd,
			java.math.BigDecimal ciOthersMaxSiHkd,
			java.math.BigDecimal ciOthersMaxSiUsd) {
		this.fullName = fullName;
		this.gender = gender;
		this.id = id;
		this.nationality = nationality;
		this.countryofResidency = countryofResidency;
		this.countryofPermanentAddress = countryofPermanentAddress;
		this.countryofResidency6Months = countryofResidency6Months;
		this.taxResidency = taxResidency;
		this.age = age;
		this.dob = dob;
		this.replaceofPolicyOption = replaceofPolicyOption;
		this.occupationClass = occupationClass;
		this.occupationName = occupationName;
		this.companyName = companyName;
		this.nationalHoldingFlag = nationalHoldingFlag;
		this.monthlyIncomeApp = monthlyIncomeApp;
		this.monthlyIncome = monthlyIncome;
		this.monthlyExpense = monthlyExpense;
		this.occupationDesc = occupationDesc;
		this.incomeMultiplier = incomeMultiplier;
		this.annualIncome = annualIncome;
		this.annualIncomeEcna = annualIncomeEcna;
		this.annualExpense = annualExpense;
		this.annualDisposableIncome = annualDisposableIncome;
		this.occupationRiskFlag = occupationRiskFlag;
		this.maxLifeSumInsuredHkd = maxLifeSumInsuredHkd;
		this.maxLifeSumInsuredUsd = maxLifeSumInsuredUsd;
		this.residencyCal = residencyCal;
		this.termBasicMaxSiHkd = termBasicMaxSiHkd;
		this.termBasicMaxSiUsd = termBasicMaxSiUsd;
		this.termRiderMaxSiHkd = termRiderMaxSiHkd;
		this.termRiderMaxSiUsd = termRiderMaxSiUsd;
		this.esRiderMaxSiHkd = esRiderMaxSiHkd;
		this.esRiderMaxSiUsd = esRiderMaxSiUsd;
		this.lipMaxSiHkd = lipMaxSiHkd;
		this.lipMaxSiUsd = lipMaxSiUsd;
		this.ciAioMaxSiHkd = ciAioMaxSiHkd;
		this.ciAioMaxSiUsd = ciAioMaxSiUsd;
		this.eliMaxSiHkd = eliMaxSiHkd;
		this.eliMaxSiUsd = eliMaxSiUsd;
		this.addMaxSiWithEcare = addMaxSiWithEcare;
		this.addMaxSiWithEcareHkd = addMaxSiWithEcareHkd;
		this.addMaxSiWithEcareUsd = addMaxSiWithEcareUsd;
		this.nonMedLifeSiHkd = nonMedLifeSiHkd;
		this.nonMedLifeSiUsd = nonMedLifeSiUsd;
		this.ciHaHbMaxSiHkd = ciHaHbMaxSiHkd;
		this.ciHaHbMaxSiUsd = ciHaHbMaxSiUsd;
		this.ciOthersMaxSiHkd = ciOthersMaxSiHkd;
		this.ciOthersMaxSiUsd = ciOthersMaxSiUsd;
	}

}