package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Owner implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Full Name")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label("Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label("ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Nationality")
	private java.lang.String nationality;
	@org.kie.api.definition.type.Label("Country of Residency")
	private java.lang.String countryofResidency;
	@org.kie.api.definition.type.Label("Country of Permanent Address")
	private java.lang.String countryofPermanentAddress;
	@org.kie.api.definition.type.Label("Country of Residency 6 Months")
	private java.lang.String countryofResidency6Months;
	@org.kie.api.definition.type.Label("Tax Residency")
	private boolean taxResidency;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("DOB")
	private java.lang.String dob;
	@org.kie.api.definition.type.Label("Replace of Policy Option")
	private boolean replaceofPolicyOption;
	@org.kie.api.definition.type.Label("Occupation Class")
	private java.lang.String occupationClass;
	@org.kie.api.definition.type.Label("Occupation Name")
	private java.lang.String occupationName;
	@org.kie.api.definition.type.Label("Company Name")
	private java.lang.String companyName;
	@org.kie.api.definition.type.Label("National Holding Flag")
	private boolean nationalHoldingFlag;

	@org.kie.api.definition.type.Label("Monthly Income")
	private java.math.BigDecimal monthlyIncomeApp;

	@org.kie.api.definition.type.Label("Disposable Monthly Income")
	private java.math.BigDecimal monthlyIncome;

	@org.kie.api.definition.type.Label("Monthly Expense")
	private java.math.BigDecimal monthlyExpense;

	@org.kie.api.definition.type.Label("Occupation Description")
	private java.lang.String occupationDesc;

	@org.kie.api.definition.type.Label("Annual Income")
	private java.math.BigDecimal annualIncome;

	@org.kie.api.definition.type.Label("Annual Income ECNA")
	private java.math.BigDecimal annualIncomeEcna;

	@org.kie.api.definition.type.Label("Annual Expense")
	private java.math.BigDecimal annualExpense;

	@org.kie.api.definition.type.Label("Annual Disposable Income")
	private java.math.BigDecimal annualDisposableIncome;

	@org.kie.api.definition.type.Label(value = "Residency after massage")
	private java.lang.String residencyCal;

	@org.kie.api.definition.type.Label(value = "occupationRiskFlag")
	private boolean occupationRiskFlag;

	public Owner() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.String getCountryofResidency() {
		return this.countryofResidency;
	}

	public void setCountryofResidency(java.lang.String countryofResidency) {
		this.countryofResidency = countryofResidency;
	}

	public java.lang.String getCountryofPermanentAddress() {
		return this.countryofPermanentAddress;
	}

	public void setCountryofPermanentAddress(
			java.lang.String countryofPermanentAddress) {
		this.countryofPermanentAddress = countryofPermanentAddress;
	}

	public java.lang.String getCountryofResidency6Months() {
		return this.countryofResidency6Months;
	}

	public void setCountryofResidency6Months(
			java.lang.String countryofResidency6Months) {
		this.countryofResidency6Months = countryofResidency6Months;
	}

	public boolean isTaxResidency() {
		return this.taxResidency;
	}

	public void setTaxResidency(boolean taxResidency) {
		this.taxResidency = taxResidency;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getDob() {
		return this.dob;
	}

	public void setDob(java.lang.String dob) {
		this.dob = dob;
	}

	public boolean isReplaceofPolicyOption() {
		return this.replaceofPolicyOption;
	}

	public void setReplaceofPolicyOption(boolean replaceofPolicyOption) {
		this.replaceofPolicyOption = replaceofPolicyOption;
	}

	public java.lang.String getOccupationClass() {
		return this.occupationClass;
	}

	public void setOccupationClass(java.lang.String occupationClass) {
		this.occupationClass = occupationClass;
	}

	public java.lang.String getOccupationName() {
		return this.occupationName;
	}

	public void setOccupationName(java.lang.String occupationName) {
		this.occupationName = occupationName;
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public boolean isNationalHoldingFlag() {
		return this.nationalHoldingFlag;
	}

	public void setNationalHoldingFlag(boolean nationalHoldingFlag) {
		this.nationalHoldingFlag = nationalHoldingFlag;
	}

	public java.math.BigDecimal getMonthlyIncomeApp() {
		return this.monthlyIncomeApp;
	}

	public void setMonthlyIncomeApp(java.math.BigDecimal monthlyIncomeApp) {
		this.monthlyIncomeApp = monthlyIncomeApp;
	}

	public java.math.BigDecimal getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.math.BigDecimal monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.math.BigDecimal getMonthlyExpense() {
		return this.monthlyExpense;
	}

	public void setMonthlyExpense(java.math.BigDecimal monthlyExpense) {
		this.monthlyExpense = monthlyExpense;
	}

	public java.lang.String getOccupationDesc() {
		return this.occupationDesc;
	}

	public void setOccupationDesc(java.lang.String occupationDesc) {
		this.occupationDesc = occupationDesc;
	}

	public java.math.BigDecimal getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(java.math.BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	public java.math.BigDecimal getAnnualIncomeEcna() {
		return this.annualIncomeEcna;
	}

	public void setAnnualIncomeEcna(java.math.BigDecimal annualIncomeEcna) {
		this.annualIncomeEcna = annualIncomeEcna;
	}

	public java.math.BigDecimal getAnnualExpense() {
		return this.annualExpense;
	}

	public void setAnnualExpense(java.math.BigDecimal annualExpense) {
		this.annualExpense = annualExpense;
	}

	public java.math.BigDecimal getAnnualDisposableIncome() {
		return this.annualDisposableIncome;
	}

	public void setAnnualDisposableIncome(
			java.math.BigDecimal annualDisposableIncome) {
		this.annualDisposableIncome = annualDisposableIncome;
	}



	public java.lang.String getResidencyCal() {
		return this.residencyCal;
	}

	public void setResidencyCal(java.lang.String residencyCal) {
		this.residencyCal = residencyCal;
	}

	public boolean isOccupationRiskFlag() {
		return this.occupationRiskFlag;
	}

	public void setOccupationRiskFlag(boolean occupationRiskFlag) {
		this.occupationRiskFlag = occupationRiskFlag;
	}

	public Owner(java.lang.String fullName, java.lang.String gender,
			java.lang.String id, java.lang.String nationality,
			java.lang.String countryofResidency,
			java.lang.String countryofPermanentAddress,
			java.lang.String countryofResidency6Months, boolean taxResidency,
			java.lang.Integer age, java.lang.String dob,
			boolean replaceofPolicyOption, java.lang.String occupationClass,
			java.lang.String occupationName, java.lang.String companyName,
			boolean nationalHoldingFlag, java.math.BigDecimal monthlyIncomeApp,
			java.math.BigDecimal monthlyIncome,
			java.math.BigDecimal monthlyExpense,
			java.lang.String occupationDesc, java.math.BigDecimal annualIncome,
			java.math.BigDecimal annualIncomeEcna,
			java.math.BigDecimal annualExpense,
			java.math.BigDecimal annualDisposableIncome,
			java.lang.String residencyCal,
			boolean occupationRiskFlag) {
		this.fullName = fullName;
		this.gender = gender;
		this.id = id;
		this.nationality = nationality;
		this.countryofResidency = countryofResidency;
		this.countryofPermanentAddress = countryofPermanentAddress;
		this.countryofResidency6Months = countryofResidency6Months;
		this.taxResidency = taxResidency;
		this.age = age;
		this.dob = dob;
		this.replaceofPolicyOption = replaceofPolicyOption;
		this.occupationClass = occupationClass;
		this.occupationName = occupationName;
		this.companyName = companyName;
		this.nationalHoldingFlag = nationalHoldingFlag;
		this.monthlyIncomeApp = monthlyIncomeApp;
		this.monthlyIncome = monthlyIncome;
		this.monthlyExpense = monthlyExpense;
		this.occupationDesc = occupationDesc;
		this.annualIncome = annualIncome;
		this.annualIncomeEcna = annualIncomeEcna;
		this.annualExpense = annualExpense;
		this.annualDisposableIncome = annualDisposableIncome;
		this.occupationRiskFlag = occupationRiskFlag;
		this.residencyCal = residencyCal;
	}

}