package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Payment Code")
	private java.lang.String paymentCode;
	@org.kie.api.definition.type.Label(value = "Multiplier")
	private java.math.BigDecimal multiplier;

	public PaymentObject() {
	}

	public java.lang.String getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(java.lang.String paymentCode) {
		this.paymentCode = paymentCode;
	}

	public java.math.BigDecimal getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(java.math.BigDecimal multiplier) {
		this.multiplier = multiplier;
	}

	public PaymentObject(java.lang.String paymentCode,
			java.math.BigDecimal multiplier) {
		this.paymentCode = paymentCode;
		this.multiplier = multiplier;
	}

}