package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Payor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Occupation Class")
	private java.lang.String occupationClass;
	@org.kie.api.definition.type.Label("Annual Income")
	private java.math.BigDecimal annualIncome;
	@org.kie.api.definition.type.Label("Rule No")
	private java.lang.String ruleNo;

	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;

	@org.kie.api.definition.type.Label("Annual Income ECNA")
	private java.math.BigDecimal annualIncomeEcna;

	@org.kie.api.definition.type.Label("Annual Expense")
	private java.math.BigDecimal annualExpense;

	@org.kie.api.definition.type.Label("Annual Disposable Income")
	private java.math.BigDecimal annualDisposableIncome;

	@org.kie.api.definition.type.Label("Total Premium to Annual Income Ratio")
	private java.math.BigDecimal premiumToIncomeRatio;

	@org.kie.api.definition.type.Label(value = "Occupation")
	private java.lang.String occupation;

	public Payor() {
	}

	public java.lang.String getOccupationClass() {
		return this.occupationClass;
	}

	public void setOccupationClass(java.lang.String occupationClass) {
		this.occupationClass = occupationClass;
	}

	public java.math.BigDecimal getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(java.math.BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	public java.lang.String getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(java.lang.String ruleNo) {
		this.ruleNo = ruleNo;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.math.BigDecimal getAnnualIncomeEcna() {
		return this.annualIncomeEcna;
	}

	public void setAnnualIncomeEcna(java.math.BigDecimal annualIncomeEcna) {
		this.annualIncomeEcna = annualIncomeEcna;
	}

	public java.math.BigDecimal getAnnualExpense() {
		return this.annualExpense;
	}

	public void setAnnualExpense(java.math.BigDecimal annualExpense) {
		this.annualExpense = annualExpense;
	}

	public java.math.BigDecimal getAnnualDisposableIncome() {
		return this.annualDisposableIncome;
	}

	public void setAnnualDisposableIncome(
			java.math.BigDecimal annualDisposableIncome) {
		this.annualDisposableIncome = annualDisposableIncome;
	}

	public java.math.BigDecimal getPremiumToIncomeRatio() {
		return this.premiumToIncomeRatio;
	}

	public void setPremiumToIncomeRatio(
			java.math.BigDecimal premiumToIncomeRatio) {
		this.premiumToIncomeRatio = premiumToIncomeRatio;
	}

	public java.lang.String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(java.lang.String occupation) {
		this.occupation = occupation;
	}

	public Payor(java.lang.String occupationClass,
			java.math.BigDecimal annualIncome, java.lang.String ruleNo,
			java.lang.String role, java.math.BigDecimal annualIncomeEcna,
			java.math.BigDecimal annualExpense,
			java.math.BigDecimal annualDisposableIncome,
			java.math.BigDecimal premiumToIncomeRatio,
			java.lang.String occupation) {
		this.occupationClass = occupationClass;
		this.annualIncome = annualIncome;
		this.ruleNo = ruleNo;
		this.role = role;
		this.annualIncomeEcna = annualIncomeEcna;
		this.annualExpense = annualExpense;
		this.annualDisposableIncome = annualDisposableIncome;
		this.premiumToIncomeRatio = premiumToIncomeRatio;
		this.occupation = occupation;
	}

}