package com.axa.dm.autouw;

import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private static List<String> inforceList;

	@org.kie.api.definition.type.Label("Lump Sum in HKD")
	private java.math.BigDecimal lumpSumHkd;

	@org.kie.api.definition.type.Label("Daily Income")
	private java.math.BigDecimal dailyIncome;

	@org.kie.api.definition.type.Label("Trans Date for calculation")
	private java.util.Date transDateCal;

	@org.kie.api.definition.type.Label("Product Series")
	private java.lang.String productSeries;

	@org.kie.api.definition.type.Label("Product Series High level")
	private java.lang.String productSeriesHigh;

	@org.kie.api.definition.type.Label("Product Series Low level")
	private java.lang.String productSeriesLow;

	@org.kie.api.definition.type.Label("Indexation")
	private boolean indexation;

	@org.kie.api.definition.type.Label("productType2")
	private java.lang.String productType2;

	@org.kie.api.definition.type.Label("productType3")
	private java.lang.String productType3;

	@org.kie.api.definition.type.Label("productType4")
	private java.lang.String productType4;

	@org.kie.api.definition.type.Label("terminationDate")
	private java.lang.String terminationDate;

	@org.kie.api.definition.type.Label("actualTerminationDate")
	private java.lang.String actualTerminationDate;

	@org.kie.api.definition.type.Label("Standard Class flag")
	private Boolean standardClass;

	@org.kie.api.definition.type.Label("Concatenated product series")
	private java.lang.String productSeriesConcat;

	@org.kie.api.definition.type.Label("Effective Date")
	private java.lang.String effectiveDate;

	@org.kie.api.definition.type.Label("Fin Limit for rule 45")
	private BigDecimal finLimit45;

	static {
		inforceList = new ArrayList();
		inforceList.add("1");
		inforceList.add("2");
		inforceList.add("5");
		inforceList.add("6");
		inforceList.add("B");
		inforceList.add("F");
	}

	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label("Policy No")
	private java.lang.String policyNo;
	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String planCode;
	@org.kie.api.definition.type.Label("Currency")
	private java.lang.String currency;
	@org.kie.api.definition.type.Label("Policy Status")
	private java.lang.String policyStatus;
	@org.kie.api.definition.type.Label("Sum Insured")
	private java.math.BigDecimal sumInsured;
	@org.kie.api.definition.type.Label("Top-up Premium")
	private java.math.BigDecimal topupPremium;
	@org.kie.api.definition.type.Label("Modal Regular Premium Exclude Topup")
	private java.math.BigDecimal modalRegularPremiumexcludeTopup;
	@org.kie.api.definition.type.Label("Payment Mode")
	private java.lang.String paymentMode;
	@org.kie.api.definition.type.Label("Lump Sum")
	private java.math.BigDecimal lumpSum;

	@org.kie.api.definition.type.Label("Initial Lump Sum Premium")
	private BigDecimal initialLumpsumPremium;

	@org.kie.api.definition.type.Label("Policy Change Effective Date")
	private java.lang.String policyChangeEffectitvedate;

	@org.kie.api.definition.type.Label("Trans Date")
	private java.lang.String transDate;

	@org.kie.api.definition.type.Label("Class Code")
	private java.lang.String classCode;

	@org.kie.api.definition.type.Label("Exclusion Code Status")
	private java.lang.String exclusionCodeStatus;

	@org.kie.api.definition.type.Label("Temp Loading")
	private java.math.BigDecimal tempLoading;

	@org.kie.api.definition.type.Label("Loading")
	private java.math.BigDecimal loading;

	@org.kie.api.definition.type.Label("Date of Submission")
	private java.lang.String dateofSubmission;

	@org.kie.api.definition.type.Label("Regular Premium")
	private java.math.BigDecimal regularPremium;

	@org.kie.api.definition.type.Label("Sum Insured in HKD")
	private java.math.BigDecimal sumInsuredHkd;

	@org.kie.api.definition.type.Label("Annual Regular Premium in HKD")
	private java.math.BigDecimal annualRegularPremiumHkd;

	@org.kie.api.definition.type.Label("currentRole")
	private java.lang.String currentRole;

	@org.kie.api.definition.type.Label("Fin Limit Multiplier")
	private java.math.BigDecimal finLimitMultiplier;

	@org.kie.api.definition.type.Label("Product Type")
	private java.lang.String productType;

	@org.kie.api.definition.type.Label("Product Group")
	private java.lang.String productGroup;

	public Policy() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(java.lang.String planCode) {
		this.planCode = planCode;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getPolicyStatus() {
		return this.policyStatus;
	}

	public void setPolicyStatus(java.lang.String policyStatus) {
		this.policyStatus = policyStatus;
	}

	public java.math.BigDecimal getSumInsured() {
		return this.sumInsured;
	}

	public void setSumInsured(java.math.BigDecimal sumInsured) {
		this.sumInsured = sumInsured;
	}

	public java.math.BigDecimal getTopupPremium() {
		return this.topupPremium;
	}

	public void setTopupPremium(java.math.BigDecimal topupPremium) {
		this.topupPremium = topupPremium;
	}

	public java.math.BigDecimal getModalRegularPremiumexcludeTopup() {
		return this.modalRegularPremiumexcludeTopup;
	}

	public void setModalRegularPremiumexcludeTopup(
			java.math.BigDecimal modalRegularPremiumexcludeTopup) {
		this.modalRegularPremiumexcludeTopup = modalRegularPremiumexcludeTopup;
	}

	public java.lang.String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(java.lang.String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public java.math.BigDecimal getLumpSum() {
		return this.lumpSum;
	}

	public void setLumpSum(java.math.BigDecimal lumpSum) {
		this.lumpSum = lumpSum;
	}

	public java.lang.String getPolicyChangeEffectitvedate() {
		return this.policyChangeEffectitvedate;
	}

	public void setPolicyChangeEffectitvedate(
			java.lang.String policyChangeEffectitvedate) {
		this.policyChangeEffectitvedate = policyChangeEffectitvedate;
	}

	public java.lang.String getTransDate() {

		return this.transDate;
	}

	public void setTransDate(java.lang.String transDate) {
		this.transDate = transDate;
	}

	public java.lang.String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(java.lang.String classCode) {
		this.classCode = classCode;
	}

	public java.lang.String getExclusionCodeStatus() {
		return this.exclusionCodeStatus;
	}

	public void setExclusionCodeStatus(java.lang.String exclusionCodeStatus) {
		this.exclusionCodeStatus = exclusionCodeStatus;
	}

	public java.math.BigDecimal getTempLoading() {
		return this.tempLoading;
	}

	public void setTempLoading(java.math.BigDecimal tempLoading) {
		this.tempLoading = tempLoading;
	}

	public java.math.BigDecimal getLoading() {
		return this.loading;
	}

	public void setLoading(java.math.BigDecimal loading) {
		this.loading = loading;
	}

	public java.math.BigDecimal getInitialLumpsumPremium() {
		return this.initialLumpsumPremium;
	}

	public void setInitialLumpsumPremium(
			java.math.BigDecimal initialLumpsumPremium) {
		this.initialLumpsumPremium = initialLumpsumPremium;
	}

	public java.lang.String getDateofSubmission() {
		return this.dateofSubmission;
	}

	public java.util.Date getDateofSubmissionCal() {
		try {
			if (this.dateofSubmission != null
					&& !this.dateofSubmission.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.dateofSubmission);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public void setDateofSubmission(java.lang.String dateofSubmission) {
		this.dateofSubmission = dateofSubmission;
	}

	public java.math.BigDecimal getRegularPremium() {
		return this.regularPremium;
	}

	public void setRegularPremium(java.math.BigDecimal regularPremium) {
		this.regularPremium = regularPremium;
	}

	public java.math.BigDecimal getSumInsuredHkd() {
		return this.sumInsuredHkd;
	}

	public void setSumInsuredHkd(java.math.BigDecimal sumInsuredHkd) {
		this.sumInsuredHkd = sumInsuredHkd;
	}

	public java.math.BigDecimal getAnnualRegularPremiumHkd() {
		return this.annualRegularPremiumHkd;
	}

	public void setAnnualRegularPremiumHkd(
			java.math.BigDecimal annualRegularPremiumHkd) {
		this.annualRegularPremiumHkd = annualRegularPremiumHkd;
	}

	public java.lang.String getCurrentRole() {
		return this.currentRole;
	}

	public void setCurrentRole(java.lang.String currentRole) {
		this.currentRole = currentRole;
	}

	public java.math.BigDecimal getFinLimitMultiplier() {
		return this.finLimitMultiplier;
	}

	public void setFinLimitMultiplier(java.math.BigDecimal finLimitMultiplier) {
		this.finLimitMultiplier = finLimitMultiplier;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(java.lang.String productGroup) {
		this.productGroup = productGroup;
	}

	public boolean isInforce(String policyStatus) {
		if (inforceList.contains(policyStatus))
			return true;
		return false;
	}

	public java.math.BigDecimal getLumpSumHkd() {
		return this.lumpSumHkd;
	}

	public void setLumpSumHkd(java.math.BigDecimal lumpSumHkd) {
		this.lumpSumHkd = lumpSumHkd;
	}

	public java.math.BigDecimal getDailyIncome() {
		return this.dailyIncome;
	}

	public void setDailyIncome(java.math.BigDecimal dailyIncome) {
		this.dailyIncome = dailyIncome;
	}

	public java.util.Date getTransDateCal() {
		try {
			java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
					.parse(this.transDate);
			return newDate;
		} catch (ParseException e) {
			e.printStackTrace();
			return null;
		}
	}

	public void setTransDateCal(java.util.Date transDateCal) {
		this.transDateCal = transDateCal;
	}

	public java.lang.String getProductSeries() {
		return this.productSeries;
	}

	public void setProductSeries(java.lang.String productSeries) {
		this.productSeries = productSeries;
	}

	public java.lang.String getProductSeriesHigh() {
		return this.productSeriesHigh;
	}

	public void setProductSeriesHigh(java.lang.String productSeriesHigh) {
		this.productSeriesHigh = productSeriesHigh;
	}

	public java.lang.String getProductSeriesLow() {
		return this.productSeriesLow;
	}

	public void setProductSeriesLow(java.lang.String productSeriesLow) {
		this.productSeriesLow = productSeriesLow;
	}

	public boolean isIndexation() {
		return this.indexation;
	}

	public void setIndexation(boolean indexation) {
		this.indexation = indexation;
	}

	public java.lang.String getProductType2() {
		return this.productType2;
	}

	public void setProductType2(java.lang.String productType2) {
		this.productType2 = productType2;
	}

	public java.lang.String getProductType3() {
		return this.productType3;
	}

	public void setProductType3(java.lang.String productType3) {
		this.productType3 = productType3;
	}

	public java.lang.String getProductType4() {
		return this.productType4;
	}

	public void setProductType4(java.lang.String productType4) {
		this.productType4 = productType4;
	}

	public java.util.Date getTerminationDateCal() {
		try {
			if (this.terminationDate != null && !this.terminationDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.terminationDate);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			e.printStackTrace();
			return null;
		}
	}

	public java.lang.String getTerminationDate() {
		return this.terminationDate;
	}

	public void setTerminationDate(java.lang.String terminationDate) {
		this.terminationDate = terminationDate;
	}

	public java.lang.String getActualTerminationDate() {
		return this.actualTerminationDate;
	}

	public java.util.Date getActualTerminationDateCal() {
		try {
			if (this.actualTerminationDate != null
					&& !this.actualTerminationDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.actualTerminationDate);
				return newDate;
			}

			return null;

		} catch (ParseException e) {
			e.printStackTrace();
			return null;
		}
	}

	public void setActualTerminationDate(java.lang.String actualTerminationDate) {
		this.actualTerminationDate = actualTerminationDate;
	}

	public boolean isValidProduct(String... strings) {
		for (String s : strings) {
			if (s.equalsIgnoreCase(this.planCode))
				return true;
			if (s.equalsIgnoreCase(this.productType))
				return true;
			if (s.equalsIgnoreCase(this.productSeries))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesHigh))
				return true;
			if (s.equalsIgnoreCase(this.productSeriesLow))
				return true;
		}
		return false;
	}

	public java.lang.Boolean getStandardClass() {
		return this.standardClass;
	}

	public void setStandardClass(java.lang.Boolean standardClass) {
		this.standardClass = standardClass;
	}

	public java.lang.String getProductSeriesConcat() {
		String s = "";
		if (this.productType != null && !"".equals(this.productType))
			s = s + "," + this.productType;

		if (this.productSeries != null && !"".equals(this.productSeries))
			s = s + "," + this.productSeries;

		if (this.productSeriesHigh != null
				&& !"".equals(this.productSeriesHigh))
			s = s + "," + this.productSeriesHigh;

		if (this.productSeriesLow != null && !"".equals(this.productSeriesLow))
			s = s + "," + this.productSeriesLow;

		return ("".equals(s)) ? s : s.substring(1);
	}

	public void setProductSeriesConcat(java.lang.String productSeriesConcat) {
		this.productSeriesConcat = productSeriesConcat;
	}

	public java.lang.String getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(java.lang.String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public java.util.Date getEffectiveDateCal() {
		try {
			if (this.effectiveDate != null && !this.effectiveDate.isEmpty()) {
				java.util.Date newDate = new SimpleDateFormat("yyyy-MM-dd")
						.parse(this.effectiveDate);
				return newDate;
			}

			return null;
		} catch (ParseException e) {
			// e.printStackTrace();
			return null;
		}
	}

	public java.math.BigDecimal getFinLimit45() {
		return this.finLimit45;
	}

	public void setFinLimit45(java.math.BigDecimal finLimit45) {
		this.finLimit45 = finLimit45;
	}

	public Policy(java.math.BigDecimal lumpSumHkd,
			java.math.BigDecimal dailyIncome, java.util.Date transDateCal,
			java.lang.String productSeries, java.lang.String productSeriesHigh,
			java.lang.String productSeriesLow, boolean indexation,
			java.lang.String productType2, java.lang.String productType3,
			java.lang.String productType4, java.lang.String terminationDate,
			java.lang.String actualTerminationDate,
			java.lang.Boolean standardClass,
			java.lang.String productSeriesConcat,
			java.lang.String effectiveDate, java.math.BigDecimal finLimit45,
			java.lang.String role, java.lang.String policyNo,
			java.lang.String planCode, java.lang.String currency,
			java.lang.String policyStatus, java.math.BigDecimal sumInsured,
			java.math.BigDecimal topupPremium,
			java.math.BigDecimal modalRegularPremiumexcludeTopup,
			java.lang.String paymentMode, java.math.BigDecimal lumpSum,
			java.math.BigDecimal initialLumpsumPremium,
			java.lang.String policyChangeEffectitvedate,
			java.lang.String transDate, java.lang.String classCode,
			java.lang.String exclusionCodeStatus,
			java.math.BigDecimal tempLoading, java.math.BigDecimal loading,
			java.lang.String dateofSubmission,
			java.math.BigDecimal regularPremium,
			java.math.BigDecimal sumInsuredHkd,
			java.math.BigDecimal annualRegularPremiumHkd,
			java.lang.String currentRole,
			java.math.BigDecimal finLimitMultiplier,
			java.lang.String productType, java.lang.String productGroup) {
		this.lumpSumHkd = lumpSumHkd;
		this.dailyIncome = dailyIncome;
		this.transDateCal = transDateCal;
		this.productSeries = productSeries;
		this.productSeriesHigh = productSeriesHigh;
		this.productSeriesLow = productSeriesLow;
		this.indexation = indexation;
		this.productType2 = productType2;
		this.productType3 = productType3;
		this.productType4 = productType4;
		this.terminationDate = terminationDate;
		this.actualTerminationDate = actualTerminationDate;
		this.standardClass = standardClass;
		this.productSeriesConcat = productSeriesConcat;
		this.effectiveDate = effectiveDate;
		this.finLimit45 = finLimit45;
		this.role = role;
		this.policyNo = policyNo;
		this.planCode = planCode;
		this.currency = currency;
		this.policyStatus = policyStatus;
		this.sumInsured = sumInsured;
		this.topupPremium = topupPremium;
		this.modalRegularPremiumexcludeTopup = modalRegularPremiumexcludeTopup;
		this.paymentMode = paymentMode;
		this.lumpSum = lumpSum;
		this.initialLumpsumPremium = initialLumpsumPremium;
		this.policyChangeEffectitvedate = policyChangeEffectitvedate;
		this.transDate = transDate;
		this.classCode = classCode;
		this.exclusionCodeStatus = exclusionCodeStatus;
		this.tempLoading = tempLoading;
		this.loading = loading;
		this.dateofSubmission = dateofSubmission;
		this.regularPremium = regularPremium;
		this.sumInsuredHkd = sumInsuredHkd;
		this.annualRegularPremiumHkd = annualRegularPremiumHkd;
		this.currentRole = currentRole;
		this.finLimitMultiplier = finLimitMultiplier;
		this.productType = productType;
		this.productGroup = productGroup;
	}
}