package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PolicyChange implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label(value = "Policy No")
	private java.lang.String policyNo;
	@org.kie.api.definition.type.Label(value = "Policy Change Type")
	private java.lang.String policyChangeType;
	@org.kie.api.definition.type.Label(value = "Policy Change Status")
	private java.lang.String policyChangeStatus;

	public PolicyChange() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getPolicyChangeType() {
		return this.policyChangeType;
	}

	public void setPolicyChangeType(java.lang.String policyChangeType) {
		this.policyChangeType = policyChangeType;
	}

	public java.lang.String getPolicyChangeStatus() {
		return this.policyChangeStatus;
	}

	public void setPolicyChangeStatus(java.lang.String policyChangeStatus) {
		this.policyChangeStatus = policyChangeStatus;
	}

	public PolicyChange(java.lang.String role, java.lang.String policyNo,
			java.lang.String policyChangeType,
			java.lang.String policyChangeStatus) {
		this.role = role;
		this.policyNo = policyNo;
		this.policyChangeType = policyChangeType;
		this.policyChangeStatus = policyChangeStatus;
	}

}