package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String planCode;
	@org.kie.api.definition.type.Label("Product Type")
	private String productType;

	@org.kie.api.definition.type.Label("Product Group")
	private java.lang.String productGroup;

	@org.kie.api.definition.type.Label("Product Series")
	private java.lang.String productSeries;

	@org.kie.api.definition.type.Label("Product Series Higher Level")
	private java.lang.String productSeriesHigh;

	@org.kie.api.definition.type.Label("Product Series Lower level")
	private java.lang.String productSeriesLow;

	@org.kie.api.definition.type.Label("Fin Limit Multiplier")
	private double finLimitMultiplier;

	@org.kie.api.definition.type.Label("Daily Income")
	private double dailyIncome;

	@org.kie.api.definition.type.Label("Indexation Flag")
	private boolean indexation;

	@org.kie.api.definition.type.Label("Fin Limit of Rule 45")
	private double finLimit45;

	public Product() {
	}

	public java.lang.String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(java.lang.String planCode) {
		this.planCode = planCode;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(java.lang.String productGroup) {
		this.productGroup = productGroup;
	}

	public java.lang.String getProductSeries() {
		return this.productSeries;
	}

	public void setProductSeries(java.lang.String productSeries) {
		this.productSeries = productSeries;
	}

	public java.lang.String getProductSeriesHigh() {
		return this.productSeriesHigh;
	}

	public void setProductSeriesHigh(java.lang.String productSeriesHigh) {
		this.productSeriesHigh = productSeriesHigh;
	}

	public java.lang.String getProductSeriesLow() {
		return this.productSeriesLow;
	}

	public void setProductSeriesLow(java.lang.String productSeriesLow) {
		this.productSeriesLow = productSeriesLow;
	}

	public double getFinLimitMultiplier() {
		return this.finLimitMultiplier;
	}

	public void setFinLimitMultiplier(double finLimitMultiplier) {
		this.finLimitMultiplier = finLimitMultiplier;
	}

	public double getDailyIncome() {
		return this.dailyIncome;
	}

	public void setDailyIncome(double dailyIncome) {
		this.dailyIncome = dailyIncome;
	}

	public boolean isIndexation() {
		return this.indexation;
	}

	public void setIndexation(boolean indexation) {
		this.indexation = indexation;
	}

	public double getFinLimit45() {
		return this.finLimit45;
	}

	public void setFinLimit45(double finLimit45) {
		this.finLimit45 = finLimit45;
	}

	public Product(java.lang.String planCode, java.lang.String productType,
			java.lang.String productGroup, java.lang.String productSeries,
			java.lang.String productSeriesHigh,
			java.lang.String productSeriesLow, double finLimitMultiplier,
			double dailyIncome, boolean indexation, double finLimit45) {
		this.planCode = planCode;
		this.productType = productType;
		this.productGroup = productGroup;
		this.productSeries = productSeries;
		this.productSeriesHigh = productSeriesHigh;
		this.productSeriesLow = productSeriesLow;
		this.finLimitMultiplier = finLimitMultiplier;
		this.dailyIncome = dailyIncome;
		this.indexation = indexation;
		this.finLimit45 = finLimit45;
	}

}