package com.axa.dm.autouw;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule2Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNoInsuredList")
	private java.util.List<java.lang.String> policyNoInsuredList;
	@org.kie.api.definition.type.Label("insuredCount")
	private int insuredCount;
	@org.kie.api.definition.type.Label("ownerCount")
	private int ownerCount;
	@org.kie.api.definition.type.Label("policyNoOwnerList")
	private java.util.List<java.lang.String> policyNoOwnerList;

	@org.kie.api.definition.type.Label("rule2InsuredProcessed")
	private boolean rule2InsuredProcessed;

	@org.kie.api.definition.type.Label("rule2OwnerProcessed")
	private boolean rule2OwnerProcessed;

	@org.kie.api.definition.type.Label("applicationNoInsuredList")
	private java.util.List<java.lang.String> applicationNoInsuredList;

	@org.kie.api.definition.type.Label("applicationNoOwnerList")
	private java.util.List<java.lang.String> applicationNoOwnerList;

	public Rule2Object() {
	}

	public java.util.List<java.lang.String> getPolicyNoInsuredList() {
		return this.policyNoInsuredList;
	}

	public void setPolicyNoInsuredList(
			java.util.List<java.lang.String> policyNoInsuredList) {
		this.policyNoInsuredList = policyNoInsuredList;
	}

	public java.util.List<java.lang.String> getPolicyNoOwnerList() {
		return this.policyNoOwnerList;
	}

	public void setPolicyNoOwnerList(
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.policyNoOwnerList = policyNoOwnerList;
	}

	public boolean isRule2InsuredProcessed() {
		return this.rule2InsuredProcessed;
	}

	public void setRule2InsuredProcessed(boolean rule2InsuredProcessed) {
		this.rule2InsuredProcessed = rule2InsuredProcessed;
	}

	public boolean isRule2OwnerProcessed() {
		return this.rule2OwnerProcessed;
	}

	public void setRule2OwnerProcessed(boolean rule2OwnerProcessed) {
		this.rule2OwnerProcessed = rule2OwnerProcessed;
	}

	public java.util.List<java.lang.String> getApplicationNoInsuredList() {
		return this.applicationNoInsuredList;
	}

	public void setApplicationNoInsuredList(
			java.util.List<java.lang.String> applicationNoInsuredList) {
		this.applicationNoInsuredList = applicationNoInsuredList;
	}

	public java.util.List<java.lang.String> getApplicationNoOwnerList() {
		return this.applicationNoOwnerList;
	}

	public void setApplicationNoOwnerList(
			java.util.List<java.lang.String> applicationNoOwnerList) {
		this.applicationNoOwnerList = applicationNoOwnerList;
	}

	public int getInsuredCount() {
		return this.insuredCount;
	}

	public void setInsuredCount(int insuredCount) {
		this.insuredCount = insuredCount;
	}

	public int getOwnerCount() {
		return this.ownerCount;
	}

	public void setOwnerCount(int ownerCount) {
		this.ownerCount = ownerCount;
	}

	public Rule2Object(java.util.List<java.lang.String> policyNoInsuredList,
			int insuredCount, int ownerCount,
			java.util.List<java.lang.String> policyNoOwnerList,
			boolean rule2InsuredProcessed, boolean rule2OwnerProcessed,
			java.util.List<java.lang.String> applicationNoInsuredList,
			java.util.List<java.lang.String> applicationNoOwnerList) {
		this.policyNoInsuredList = policyNoInsuredList;
		this.insuredCount = insuredCount;
		this.ownerCount = ownerCount;
		this.policyNoOwnerList = policyNoOwnerList;
		this.rule2InsuredProcessed = rule2InsuredProcessed;
		this.rule2OwnerProcessed = rule2OwnerProcessed;
		this.applicationNoInsuredList = applicationNoInsuredList;
		this.applicationNoOwnerList = applicationNoOwnerList;
	}

}