package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule23Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Current Insured Flag")
	private boolean currentInsuredFlag;
	@org.kie.api.definition.type.Label(value = "Current Owner Flag")
	private boolean currentOwnerFlag;

	public Rule23Obj() {
	}

	public boolean isCurrentInsuredFlag() {
		return this.currentInsuredFlag;
	}

	public void setCurrentInsuredFlag(boolean currentInsuredFlag) {
		this.currentInsuredFlag = currentInsuredFlag;
	}

	public boolean isCurrentOwnerFlag() {
		return this.currentOwnerFlag;
	}

	public void setCurrentOwnerFlag(boolean currentOwnerFlag) {
		this.currentOwnerFlag = currentOwnerFlag;
	}

	public Rule23Obj(boolean currentInsuredFlag, boolean currentOwnerFlag) {
		this.currentInsuredFlag = currentInsuredFlag;
		this.currentOwnerFlag = currentOwnerFlag;
	}

}