package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule25Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNoInsuredList")
	private java.util.List<java.lang.String> policyNoInsuredList;
	@org.kie.api.definition.type.Label("policyNoOwnerList")
	private java.util.List<java.lang.String> policyNoOwnerList;
	@org.kie.api.definition.type.Label("claimNoOwnerList")
	private java.util.List<java.lang.String> claimNoOwnerList;
	@org.kie.api.definition.type.Label("claimNoInsuredList")
	private java.util.List<java.lang.String> claimNoInsuredList;
	@org.kie.api.definition.type.Label("rule25InsuredProcessed")
	private boolean rule25InsuredProcessed;

	@org.kie.api.definition.type.Label("rule25OwnerProcessed")
	private boolean rule25OwnerProcessed;

	@org.kie.api.definition.type.Label("lastYmonthsInsuredList")
	private java.util.List<java.lang.String> lastYmonthsInsuredList;

	@org.kie.api.definition.type.Label("lastYmonthsOwnerList")
	private java.util.List<java.lang.String> lastYmonthsOwnerList;

	@org.kie.api.definition.type.Label(value = "dateOfClaimInsuredList")
	private java.util.List<java.util.Date> dateOfClaimInsuredList;

	@org.kie.api.definition.type.Label(value = "dateOfClaimOwnerList")
	private java.util.List<java.util.Date> dateOfClaimOwnerList;

	public Rule25Object() {
	}

	public java.util.List<java.lang.String> getPolicyNoInsuredList() {
		return this.policyNoInsuredList;
	}

	public void setPolicyNoInsuredList(
			java.util.List<java.lang.String> policyNoInsuredList) {
		this.policyNoInsuredList = policyNoInsuredList;
	}

	public java.util.List<java.lang.String> getPolicyNoOwnerList() {
		return this.policyNoOwnerList;
	}

	public void setPolicyNoOwnerList(
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.policyNoOwnerList = policyNoOwnerList;
	}

	public java.util.List<java.lang.String> getClaimNoOwnerList() {
		return this.claimNoOwnerList;
	}

	public void setClaimNoOwnerList(
			java.util.List<java.lang.String> claimNoOwnerList) {
		this.claimNoOwnerList = claimNoOwnerList;
	}

	public java.util.List<java.lang.String> getClaimNoInsuredList() {
		return this.claimNoInsuredList;
	}

	public void setClaimNoInsuredList(
			java.util.List<java.lang.String> claimNoInsuredList) {
		this.claimNoInsuredList = claimNoInsuredList;
	}

	public boolean isRule25InsuredProcessed() {
		return this.rule25InsuredProcessed;
	}

	public void setRule25InsuredProcessed(boolean rule25InsuredProcessed) {
		this.rule25InsuredProcessed = rule25InsuredProcessed;
	}

	public boolean isRule25OwnerProcessed() {
		return this.rule25OwnerProcessed;
	}

	public void setRule25OwnerProcessed(boolean rule25OwnerProcessed) {
		this.rule25OwnerProcessed = rule25OwnerProcessed;
	}

	public java.util.List<java.lang.String> getLastYmonthsInsuredList() {
		return this.lastYmonthsInsuredList;
	}

	public void setLastYmonthsInsuredList(
			java.util.List<java.lang.String> lastYmonthsInsuredList) {
		this.lastYmonthsInsuredList = lastYmonthsInsuredList;
	}

	public java.util.List<java.lang.String> getLastYmonthsOwnerList() {
		return this.lastYmonthsOwnerList;
	}

	public void setLastYmonthsOwnerList(
			java.util.List<java.lang.String> lastYmonthsOwnerList) {
		this.lastYmonthsOwnerList = lastYmonthsOwnerList;
	}

	public java.util.List<java.util.Date> getDateOfClaimInsuredList() {
		return this.dateOfClaimInsuredList;
	}

	public void setDateOfClaimInsuredList(
			java.util.List<java.util.Date> dateOfClaimInsuredList) {
		this.dateOfClaimInsuredList = dateOfClaimInsuredList;
	}

	public java.util.List<java.util.Date> getDateOfClaimOwnerList() {
		return this.dateOfClaimOwnerList;
	}

	public void setDateOfClaimOwnerList(
			java.util.List<java.util.Date> dateOfClaimOwnerList) {
		this.dateOfClaimOwnerList = dateOfClaimOwnerList;
	}

	public Rule25Object(java.util.List<java.lang.String> policyNoInsuredList,
			java.util.List<java.lang.String> policyNoOwnerList,
			java.util.List<java.lang.String> claimNoOwnerList,
			java.util.List<java.lang.String> claimNoInsuredList,
			boolean rule25InsuredProcessed, boolean rule25OwnerProcessed,
			java.util.List<java.lang.String> lastYmonthsInsuredList,
			java.util.List<java.lang.String> lastYmonthsOwnerList,
			java.util.List<java.util.Date> dateOfClaimInsuredList,
			java.util.List<java.util.Date> dateOfClaimOwnerList) {
		this.policyNoInsuredList = policyNoInsuredList;
		this.policyNoOwnerList = policyNoOwnerList;
		this.claimNoOwnerList = claimNoOwnerList;
		this.claimNoInsuredList = claimNoInsuredList;
		this.rule25InsuredProcessed = rule25InsuredProcessed;
		this.rule25OwnerProcessed = rule25OwnerProcessed;
		this.lastYmonthsInsuredList = lastYmonthsInsuredList;
		this.lastYmonthsOwnerList = lastYmonthsOwnerList;
		this.dateOfClaimInsuredList = dateOfClaimInsuredList;
		this.dateOfClaimOwnerList = dateOfClaimOwnerList;
	}

}