package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule24Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Claim List for result")
	private java.util.List<com.axa.dm.autouw.Claim> resultClaimList;

	@org.kie.api.definition.type.Label(value = "Claim List of Owner for result")
	private java.util.List<com.axa.dm.autouw.Claim> resultOwnerClaimList;

	public Rule24Obj() {
	}

	public java.util.List<com.axa.dm.autouw.Claim> getResultClaimList() {
		return this.resultClaimList;
	}

	public void setResultClaimList(
			java.util.List<com.axa.dm.autouw.Claim> resultClaimList) {
		this.resultClaimList = resultClaimList;
	}

	public java.util.List<com.axa.dm.autouw.Claim> getResultOwnerClaimList() {
		return this.resultOwnerClaimList;
	}

	public void setResultOwnerClaimList(
			java.util.List<com.axa.dm.autouw.Claim> resultOwnerClaimList) {
		this.resultOwnerClaimList = resultOwnerClaimList;
	}

	public Rule24Obj(java.util.List<com.axa.dm.autouw.Claim> resultClaimList,
			java.util.List<com.axa.dm.autouw.Claim> resultOwnerClaimList) {
		this.resultClaimList = resultClaimList;
		this.resultOwnerClaimList = resultOwnerClaimList;
	}

}