package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule17AObj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Aggregate Daily Income")
	private java.math.BigDecimal aggDailyIncome;

	@org.kie.api.definition.type.Label(value = "Hospital Sure Flag")
	private boolean hospitalSure;

	public Rule17AObj() {
	}

	public java.math.BigDecimal getAggDailyIncome() {
		return this.aggDailyIncome;
	}

	public void setAggDailyIncome(java.math.BigDecimal aggDailyIncome) {
		this.aggDailyIncome = aggDailyIncome;
	}

	public boolean isHospitalSure() {
		return this.hospitalSure;
	}

	public void setHospitalSure(boolean hospitalSure) {
		this.hospitalSure = hospitalSure;
	}

	public Rule17AObj(java.math.BigDecimal aggDailyIncome, boolean hospitalSure) {
		this.aggDailyIncome = aggDailyIncome;
		this.hospitalSure = hospitalSure;
	}

}