package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule21Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNoInsuredList")
	private java.util.List<java.lang.String> policyNoInsuredList;
	@org.kie.api.definition.type.Label("policyNoOwnerList")
	private java.util.List<java.lang.String> policyNoOwnerList;
	@org.kie.api.definition.type.Label("specialCaseTypeInsuredList")
	private java.util.List<java.lang.String> specialCaseTypeInsuredList;
	@org.kie.api.definition.type.Label("specialCaseTypeOwnerList")
	private java.util.List<java.lang.String> specialCaseTypeOwnerList;
	@org.kie.api.definition.type.Label(value = "insuredfullNameList")
	private java.util.List<java.lang.String> insuredfullNameList;

	@org.kie.api.definition.type.Label(value = "OwnerfullNameList")
	private java.util.List<java.lang.String> ownerfullNameList;

	public Rule21Object() {
	}

	public java.util.List<java.lang.String> getPolicyNoInsuredList() {
		return this.policyNoInsuredList;
	}

	public void setPolicyNoInsuredList(
			java.util.List<java.lang.String> policyNoInsuredList) {
		this.policyNoInsuredList = policyNoInsuredList;
	}

	public java.util.List<java.lang.String> getPolicyNoOwnerList() {
		return this.policyNoOwnerList;
	}

	public void setPolicyNoOwnerList(
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.policyNoOwnerList = policyNoOwnerList;
	}

	public java.util.List<java.lang.String> getSpecialCaseTypeInsuredList() {
		return this.specialCaseTypeInsuredList;
	}

	public void setSpecialCaseTypeInsuredList(
			java.util.List<java.lang.String> specialCaseTypeInsuredList) {
		this.specialCaseTypeInsuredList = specialCaseTypeInsuredList;
	}

	public java.util.List<java.lang.String> getSpecialCaseTypeOwnerList() {
		return this.specialCaseTypeOwnerList;
	}

	public void setSpecialCaseTypeOwnerList(
			java.util.List<java.lang.String> specialCaseTypeOwnerList) {
		this.specialCaseTypeOwnerList = specialCaseTypeOwnerList;
	}

	public java.util.List<java.lang.String> getInsuredfullNameList() {
		return this.insuredfullNameList;
	}

	public void setInsuredfullNameList(
			java.util.List<java.lang.String> insuredfullNameList) {
		this.insuredfullNameList = insuredfullNameList;
	}

	public java.util.List<java.lang.String> getOwnerfullNameList() {
		return this.ownerfullNameList;
	}

	public void setOwnerfullNameList(
			java.util.List<java.lang.String> ownerfullNameList) {
		this.ownerfullNameList = ownerfullNameList;
	}

	public Rule21Object(java.util.List<java.lang.String> policyNoInsuredList,
			java.util.List<java.lang.String> policyNoOwnerList,
			java.util.List<java.lang.String> specialCaseTypeInsuredList,
			java.util.List<java.lang.String> specialCaseTypeOwnerList,
			java.util.List<java.lang.String> insuredfullNameList,
			java.util.List<java.lang.String> ownerfullNameList) {
		this.policyNoInsuredList = policyNoInsuredList;
		this.policyNoOwnerList = policyNoOwnerList;
		this.specialCaseTypeInsuredList = specialCaseTypeInsuredList;
		this.specialCaseTypeOwnerList = specialCaseTypeOwnerList;
		this.insuredfullNameList = insuredfullNameList;
		this.ownerfullNameList = ownerfullNameList;
	}

}