package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule1Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Message 1")
	private java.lang.String msg1;
	@org.kie.api.definition.type.Label("Message 2")
	private java.lang.String msg2;
	@org.kie.api.definition.type.Label("Message 3")
	private java.lang.String msg3;
	@org.kie.api.definition.type.Label("Message 4")
	private java.lang.String msg4;
	@org.kie.api.definition.type.Label("Message 5")
	private java.lang.String msg5;
	@org.kie.api.definition.type.Label("Message 6")
	private java.lang.String msg6;
	@org.kie.api.definition.type.Label("Message 7")
	private java.lang.String msg7;

	@org.kie.api.definition.type.Label("Message 8")
	private java.lang.String msg8;

	@org.kie.api.definition.type.Label("Message 9")
	private java.lang.String msg9;

	@org.kie.api.definition.type.Label("Message 10")
	private java.lang.String msg10;

	@org.kie.api.definition.type.Label(value = "Temp Total Life Sum Insured in HKD")
	private java.math.BigDecimal totalLifeSiHkdTemp;

	@org.kie.api.definition.type.Label(value = "Temp Current Application Life Sum Insured in HKD")
	private java.math.BigDecimal currentLifeSiHkdTemp;

	public Rule1Obj() {
	}

	public java.lang.String getMsg1() {
		return this.msg1;
	}

	public void setMsg1(java.lang.String msg1) {
		this.msg1 = msg1;
	}

	public java.lang.String getMsg2() {
		return this.msg2;
	}

	public void setMsg2(java.lang.String msg2) {
		this.msg2 = msg2;
	}

	public java.lang.String getMsg3() {
		return this.msg3;
	}

	public void setMsg3(java.lang.String msg3) {
		this.msg3 = msg3;
	}

	public java.lang.String getMsg4() {
		return this.msg4;
	}

	public void setMsg4(java.lang.String msg4) {
		this.msg4 = msg4;
	}

	public java.lang.String getMsg5() {
		return this.msg5;
	}

	public void setMsg5(java.lang.String msg5) {
		this.msg5 = msg5;
	}

	public java.lang.String getMsg6() {
		return this.msg6;
	}

	public void setMsg6(java.lang.String msg6) {
		this.msg6 = msg6;
	}

	public java.lang.String getMsg7() {
		return this.msg7;
	}

	public void setMsg7(java.lang.String msg7) {
		this.msg7 = msg7;
	}

	public java.lang.String getMsg8() {
		return this.msg8;
	}

	public void setMsg8(java.lang.String msg8) {
		this.msg8 = msg8;
	}

	public java.lang.String getMsg9() {
		return this.msg9;
	}

	public void setMsg9(java.lang.String msg9) {
		this.msg9 = msg9;
	}

	public java.lang.String getMsg10() {
		return this.msg10;
	}

	public void setMsg10(java.lang.String msg10) {
		this.msg10 = msg10;
	}

	public java.math.BigDecimal getTotalLifeSiHkdTemp() {
		return this.totalLifeSiHkdTemp;
	}

	public void setTotalLifeSiHkdTemp(java.math.BigDecimal totalLifeSiHkdTemp) {
		this.totalLifeSiHkdTemp = totalLifeSiHkdTemp;
	}

	public java.math.BigDecimal getCurrentLifeSiHkdTemp() {
		return this.currentLifeSiHkdTemp;
	}

	public void setCurrentLifeSiHkdTemp(
			java.math.BigDecimal currentLifeSiHkdTemp) {
		this.currentLifeSiHkdTemp = currentLifeSiHkdTemp;
	}

	public Rule1Obj(java.lang.String msg1, java.lang.String msg2,
			java.lang.String msg3, java.lang.String msg4,
			java.lang.String msg5, java.lang.String msg6,
			java.lang.String msg7, java.lang.String msg8,
			java.lang.String msg9, java.lang.String msg10,
			java.math.BigDecimal totalLifeSiHkdTemp,
			java.math.BigDecimal currentLifeSiHkdTemp) {
		this.msg1 = msg1;
		this.msg2 = msg2;
		this.msg3 = msg3;
		this.msg4 = msg4;
		this.msg5 = msg5;
		this.msg6 = msg6;
		this.msg7 = msg7;
		this.msg8 = msg8;
		this.msg9 = msg9;
		this.msg10 = msg10;
		this.totalLifeSiHkdTemp = totalLifeSiHkdTemp;
		this.currentLifeSiHkdTemp = currentLifeSiHkdTemp;
	}

}