package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule20Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("rule20OwnerProcessed")
	private boolean rule20OwnerProcessed;
	@org.kie.api.definition.type.Label("rule20InsuredProcessed")
	private boolean rule20InsuredProcessed;

	@org.kie.api.definition.type.Label("condition1Processed")
	private boolean condition1Processed;

	@org.kie.api.definition.type.Label("condition2Processed")
	private boolean condition2Processed;

	@org.kie.api.definition.type.Label("policyNoInsuredList")
	private java.util.List<java.lang.String> policyNoInsuredList;

	@org.kie.api.definition.type.Label("policyNoOwnerList")
	private java.util.List<java.lang.String> policyNoOwnerList;

	@org.kie.api.definition.type.Label("withinNyearsInsuredList")
	private java.util.List<java.lang.String> withinNyearsInsuredList;

	@org.kie.api.definition.type.Label("withinNyearsOwnerList")
	private java.util.List<java.lang.String> withinNyearsOwnerList;

	@org.kie.api.definition.type.Label("statusCodeInsuredList")
	private java.util.List<java.lang.String> statusCodeInsuredList;

	@org.kie.api.definition.type.Label("statusCodeOwnerList")
	private java.util.List<java.lang.String> statusCodeOwnerList;

	@org.kie.api.definition.type.Label(value = "insuredFullName")
	private java.lang.String insuredFullName;

	@org.kie.api.definition.type.Label(value = "ownerFullName")
	private java.lang.String ownerFullName;

	public Rule20Object() {
	}

	public boolean isRule20OwnerProcessed() {
		return this.rule20OwnerProcessed;
	}

	public void setRule20OwnerProcessed(boolean rule20OwnerProcessed) {
		this.rule20OwnerProcessed = rule20OwnerProcessed;
	}

	public boolean isRule20InsuredProcessed() {
		return this.rule20InsuredProcessed;
	}

	public void setRule20InsuredProcessed(boolean rule20InsuredProcessed) {
		this.rule20InsuredProcessed = rule20InsuredProcessed;
	}

	public boolean isCondition1Processed() {
		return this.condition1Processed;
	}

	public void setCondition1Processed(boolean condition1Processed) {
		this.condition1Processed = condition1Processed;
	}

	public boolean isCondition2Processed() {
		return this.condition2Processed;
	}

	public void setCondition2Processed(boolean condition2Processed) {
		this.condition2Processed = condition2Processed;
	}

	public java.util.List<java.lang.String> getPolicyNoInsuredList() {
		return this.policyNoInsuredList;
	}

	public void setPolicyNoInsuredList(
			java.util.List<java.lang.String> policyNoInsuredList) {
		this.policyNoInsuredList = policyNoInsuredList;
	}

	public java.util.List<java.lang.String> getPolicyNoOwnerList() {
		return this.policyNoOwnerList;
	}

	public void setPolicyNoOwnerList(
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.policyNoOwnerList = policyNoOwnerList;
	}

	public java.util.List<java.lang.String> getWithinNyearsInsuredList() {
		return this.withinNyearsInsuredList;
	}

	public void setWithinNyearsInsuredList(
			java.util.List<java.lang.String> withinNyearsInsuredList) {
		this.withinNyearsInsuredList = withinNyearsInsuredList;
	}

	public java.util.List<java.lang.String> getWithinNyearsOwnerList() {
		return this.withinNyearsOwnerList;
	}

	public void setWithinNyearsOwnerList(
			java.util.List<java.lang.String> withinNyearsOwnerList) {
		this.withinNyearsOwnerList = withinNyearsOwnerList;
	}

	public java.util.List<java.lang.String> getStatusCodeInsuredList() {
		return this.statusCodeInsuredList;
	}

	public void setStatusCodeInsuredList(
			java.util.List<java.lang.String> statusCodeInsuredList) {
		this.statusCodeInsuredList = statusCodeInsuredList;
	}

	public java.util.List<java.lang.String> getStatusCodeOwnerList() {
		return this.statusCodeOwnerList;
	}

	public void setStatusCodeOwnerList(
			java.util.List<java.lang.String> statusCodeOwnerList) {
		this.statusCodeOwnerList = statusCodeOwnerList;
	}

	public java.lang.String getInsuredFullName() {
		return this.insuredFullName;
	}

	public void setInsuredFullName(java.lang.String insuredFullName) {
		this.insuredFullName = insuredFullName;
	}

	public java.lang.String getOwnerFullName() {
		return this.ownerFullName;
	}

	public void setOwnerFullName(java.lang.String ownerFullName) {
		this.ownerFullName = ownerFullName;
	}

	public Rule20Object(boolean rule20OwnerProcessed,
			boolean rule20InsuredProcessed, boolean condition1Processed,
			boolean condition2Processed,
			java.util.List<java.lang.String> policyNoInsuredList,
			java.util.List<java.lang.String> policyNoOwnerList,
			java.util.List<java.lang.String> withinNyearsInsuredList,
			java.util.List<java.lang.String> withinNyearsOwnerList,
			java.util.List<java.lang.String> statusCodeInsuredList,
			java.util.List<java.lang.String> statusCodeOwnerList,
			java.lang.String insuredFullName, java.lang.String ownerFullName) {
		this.rule20OwnerProcessed = rule20OwnerProcessed;
		this.rule20InsuredProcessed = rule20InsuredProcessed;
		this.condition1Processed = condition1Processed;
		this.condition2Processed = condition2Processed;
		this.policyNoInsuredList = policyNoInsuredList;
		this.policyNoOwnerList = policyNoOwnerList;
		this.withinNyearsInsuredList = withinNyearsInsuredList;
		this.withinNyearsOwnerList = withinNyearsOwnerList;
		this.statusCodeInsuredList = statusCodeInsuredList;
		this.statusCodeOwnerList = statusCodeOwnerList;
		this.insuredFullName = insuredFullName;
		this.ownerFullName = ownerFullName;
	}

}