package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule26Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("rule26InsuredProcessed")
	private boolean rule26InsuredProcessed;
	@org.kie.api.definition.type.Label("rule26OwnerProcessed")
	private boolean rule26OwnerProcessed;

	@org.kie.api.definition.type.Label(value = "claimInsuredList")
	private java.util.List<java.lang.String> claimInsuredList;

	@org.kie.api.definition.type.Label(value = "claimOwnerList")
	private java.util.List<java.lang.String> claimOwnerList;

	@org.kie.api.definition.type.Label(value = "policyNoInsuredList")
	private java.util.List<java.lang.String> policyNoInsuredList;

	@org.kie.api.definition.type.Label(value = "policyNoOwnerList")
	private java.util.List<java.lang.String> policyNoOwnerList;

	public Rule26Object() {
	}

	public boolean isRule26InsuredProcessed() {
		return this.rule26InsuredProcessed;
	}

	public void setRule26InsuredProcessed(boolean rule26InsuredProcessed) {
		this.rule26InsuredProcessed = rule26InsuredProcessed;
	}

	public boolean isRule26OwnerProcessed() {
		return this.rule26OwnerProcessed;
	}

	public void setRule26OwnerProcessed(boolean rule26OwnerProcessed) {
		this.rule26OwnerProcessed = rule26OwnerProcessed;
	}

	public java.util.List<java.lang.String> getClaimInsuredList() {
		return this.claimInsuredList;
	}

	public void setClaimInsuredList(
			java.util.List<java.lang.String> claimInsuredList) {
		this.claimInsuredList = claimInsuredList;
	}

	public java.util.List<java.lang.String> getClaimOwnerList() {
		return this.claimOwnerList;
	}

	public void setClaimOwnerList(
			java.util.List<java.lang.String> claimOwnerList) {
		this.claimOwnerList = claimOwnerList;
	}

	public java.util.List<java.lang.String> getPolicyNoInsuredList() {
		return this.policyNoInsuredList;
	}

	public void setPolicyNoInsuredList(
			java.util.List<java.lang.String> policyNoInsuredList) {
		this.policyNoInsuredList = policyNoInsuredList;
	}

	public java.util.List<java.lang.String> getPolicyNoOwnerList() {
		return this.policyNoOwnerList;
	}

	public void setPolicyNoOwnerList(
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.policyNoOwnerList = policyNoOwnerList;
	}

	public Rule26Object(boolean rule26InsuredProcessed,
			boolean rule26OwnerProcessed,
			java.util.List<java.lang.String> claimInsuredList,
			java.util.List<java.lang.String> claimOwnerList,
			java.util.List<java.lang.String> policyNoInsuredList,
			java.util.List<java.lang.String> policyNoOwnerList) {
		this.rule26InsuredProcessed = rule26InsuredProcessed;
		this.rule26OwnerProcessed = rule26OwnerProcessed;
		this.claimInsuredList = claimInsuredList;
		this.claimOwnerList = claimOwnerList;
		this.policyNoInsuredList = policyNoInsuredList;
		this.policyNoOwnerList = policyNoOwnerList;
	}

}