package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule55Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("totalAnnualPremium")
	private java.math.BigDecimal totalAnnualPremium;
	@org.kie.api.definition.type.Label("initFlag")
	private boolean initFlag;

	@org.kie.api.definition.type.Label(value = "condition1Processed")
	private boolean condition1Processed;

	@org.kie.api.definition.type.Label(value = "condition2Processed")
	private boolean condition2Processed;

	public Rule55Object() {
	}

	public java.math.BigDecimal getTotalAnnualPremium() {
		return this.totalAnnualPremium;
	}

	public void setTotalAnnualPremium(java.math.BigDecimal totalAnnualPremium) {
		this.totalAnnualPremium = totalAnnualPremium;
	}

	public boolean isInitFlag() {
		return this.initFlag;
	}

	public void setInitFlag(boolean initFlag) {
		this.initFlag = initFlag;
	}

	public boolean isCondition1Processed() {
		return this.condition1Processed;
	}

	public void setCondition1Processed(boolean condition1Processed) {
		this.condition1Processed = condition1Processed;
	}

	public boolean isCondition2Processed() {
		return this.condition2Processed;
	}

	public void setCondition2Processed(boolean condition2Processed) {
		this.condition2Processed = condition2Processed;
	}

	public Rule55Object(java.math.BigDecimal totalAnnualPremium,
			boolean initFlag, boolean condition1Processed,
			boolean condition2Processed) {
		this.totalAnnualPremium = totalAnnualPremium;
		this.initFlag = initFlag;
		this.condition1Processed = condition1Processed;
		this.condition2Processed = condition2Processed;
	}

}