package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule45Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Insured Individual")
	private com.axa.dm.autouw.InsuredIndividual insuredIndividual;
	@org.kie.api.definition.type.Label("Owner Individual")
	private com.axa.dm.autouw.OwnerIndividual ownerIndividual;

	@org.kie.api.definition.type.Label(value = "Is insured")
	private boolean isInsured;

	@org.kie.api.definition.type.Label(value = "Is owner")
	private boolean isOwner;

	public Rule45Obj() {
	}

	public com.axa.dm.autouw.InsuredIndividual getInsuredIndividual() {
		return this.insuredIndividual;
	}

	public void setInsuredIndividual(
			com.axa.dm.autouw.InsuredIndividual insuredIndividual) {
		this.insuredIndividual = insuredIndividual;
	}

	public com.axa.dm.autouw.OwnerIndividual getOwnerIndividual() {
		return this.ownerIndividual;
	}

	public void setOwnerIndividual(
			com.axa.dm.autouw.OwnerIndividual ownerIndividual) {
		this.ownerIndividual = ownerIndividual;
	}

	public boolean isIsInsured() {
		return this.isInsured;
	}

	public void setIsInsured(boolean isInsured) {
		this.isInsured = isInsured;
	}

	public boolean isIsOwner() {
		return this.isOwner;
	}

	public void setIsOwner(boolean isOwner) {
		this.isOwner = isOwner;
	}

	public Rule45Obj(com.axa.dm.autouw.InsuredIndividual insuredIndividual,
			com.axa.dm.autouw.OwnerIndividual ownerIndividual,
			boolean isInsured, boolean isOwner) {
		this.insuredIndividual = insuredIndividual;
		this.ownerIndividual = ownerIndividual;
		this.isInsured = isInsured;
		this.isOwner = isOwner;
	}

}