package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Rule No")
	private java.lang.String ruleNo;
	@org.kie.api.definition.type.Label("Rule Name")
	private java.lang.String ruleName;
	@org.kie.api.definition.type.Label("Message to Client English")
	private java.lang.String messageToClientEng;
	@org.kie.api.definition.type.Label("Message to Client Chinese")
	private java.lang.String messageToClientChi;

	public RuleObject() {
	}

	public java.lang.String getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(java.lang.String ruleNo) {
		this.ruleNo = ruleNo;
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}

	public java.lang.String getMessageToClientEng() {
		return this.messageToClientEng;
	}

	public void setMessageToClientEng(java.lang.String messageToClientEng) {
		this.messageToClientEng = messageToClientEng;
	}

	public java.lang.String getMessageToClientChi() {
		return this.messageToClientChi;
	}

	public void setMessageToClientChi(java.lang.String messageToClientChi) {
		this.messageToClientChi = messageToClientChi;
	}

	public RuleObject(java.lang.String ruleNo, java.lang.String ruleName,
			java.lang.String messageToClientEng,
			java.lang.String messageToClientChi) {
		this.ruleNo = ruleNo;
		this.ruleName = ruleName;
		this.messageToClientEng = messageToClientEng;
		this.messageToClientChi = messageToClientChi;
	}

}