package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule42Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "beneficiaryRelationshipList")
	private java.util.List<java.lang.String> beneficiaryRelationshipList;

	public Rule42Object() {
	}

	public java.util.List<java.lang.String> getBeneficiaryRelationshipList() {
		return this.beneficiaryRelationshipList;
	}

	public void setBeneficiaryRelationshipList(
			java.util.List<java.lang.String> beneficiaryRelationshipList) {
		this.beneficiaryRelationshipList = beneficiaryRelationshipList;
	}

	public Rule42Object(
			java.util.List<java.lang.String> beneficiaryRelationshipList) {
		this.beneficiaryRelationshipList = beneficiaryRelationshipList;
	}

}