package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule31Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("sumInsuredList")
	private java.util.List<java.math.BigDecimal> sumInsuredList;
	@org.kie.api.definition.type.Label("planCodeList")
	private java.util.List<java.lang.String> planCodeList;

	@org.kie.api.definition.type.Label(value = "maxSumInsuredList")
	private java.util.List<java.math.BigDecimal> maxSumInsuredList;

	public Rule31Object() {
	}

	public java.util.List<java.math.BigDecimal> getSumInsuredList() {
		return this.sumInsuredList;
	}

	public void setSumInsuredList(
			java.util.List<java.math.BigDecimal> sumInsuredList) {
		this.sumInsuredList = sumInsuredList;
	}

	public java.util.List<java.lang.String> getPlanCodeList() {
		return this.planCodeList;
	}

	public void setPlanCodeList(java.util.List<java.lang.String> planCodeList) {
		this.planCodeList = planCodeList;
	}

	public java.util.List<java.math.BigDecimal> getMaxSumInsuredList() {
		return this.maxSumInsuredList;
	}

	public void setMaxSumInsuredList(
			java.util.List<java.math.BigDecimal> maxSumInsuredList) {
		this.maxSumInsuredList = maxSumInsuredList;
	}

	public Rule31Object(java.util.List<java.math.BigDecimal> sumInsuredList,
			java.util.List<java.lang.String> planCodeList,
			java.util.List<java.math.BigDecimal> maxSumInsuredList) {
		this.sumInsuredList = sumInsuredList;
		this.planCodeList = planCodeList;
		this.maxSumInsuredList = maxSumInsuredList;
	}

}