package com.axa.dm.autouw;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule9Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Check Lump Sum Processed?")
	private boolean checkLumpSumProcessed;
	@org.kie.api.definition.type.Label("Fail Reason List")
	private java.util.List<java.lang.String> failReasonList;
	@org.kie.api.definition.type.Label("Check Annual Regular Premium Processed?")
	private boolean checkAnnualRegularPremiumProcessed;

	@org.kie.api.definition.type.Label("Check Annual Regular Premium Plus Processed")
	private boolean checkAnnualRegularPremiumPlusProcessed;

	@org.kie.api.definition.type.Label(value = "Check Aggregate Annual Regular Premium Processed?")
	private boolean checkAggAnnualRegularPremiumProcessed;
	
	@org.kie.api.definition.type.Label("Total Annual Regular Premium")
	private java.math.BigDecimal totalAnnualRegularPremium;
	
	@org.kie.api.definition.type.Label("Targeted Policy List")
	private java.util.List<com.axa.dm.autouw.Policy> targetPolicyList;
	
	@org.kie.api.definition.type.Label("Targeted Application List")
	private java.util.List<com.axa.dm.autouw.Application> targetAppList;

	public Rule9Obj() {
	}
	
	public java.util.List<com.axa.dm.autouw.Policy> getTargetPolicyList(){
		return this.targetPolicyList;
	}
	
	public void setTargetPolicyList(java.util.List<com.axa.dm.autouw.Policy> targetPolicyList){
		this.targetPolicyList = targetPolicyList;
	}
	
	public java.util.List<com.axa.dm.autouw.Application> getTargetAppList(){
		return this.targetAppList;
	}
	
	public void setTargetAppList(java.util.List<com.axa.dm.autouw.Application> targetAppList){
		this.targetAppList = targetAppList;
	}
	
	public java.math.BigDecimal getTotalAnnualRegularPremium(){
			return this.totalAnnualRegularPremium;
	}
	
	public void setTotalAnnualRegularPremium(java.math.BigDecimal totalAnnualRegularPremium){
			this.totalAnnualRegularPremium = totalAnnualRegularPremium;
	}

	public boolean isCheckLumpSumProcessed() {
		return this.checkLumpSumProcessed;
	}

	public void setCheckLumpSumProcessed(boolean checkLumpSumProcessed) {
		this.checkLumpSumProcessed = checkLumpSumProcessed;
	}

	public java.util.List<java.lang.String> getFailReasonList() {
		return this.failReasonList;
	}

	public void setFailReasonList(
			java.util.List<java.lang.String> failReasonList) {
		this.failReasonList = failReasonList;
	}

	public boolean isCheckAnnualRegularPremiumProcessed() {
		return this.checkAnnualRegularPremiumProcessed;
	}

	public void setCheckAnnualRegularPremiumProcessed(
			boolean checkAnnualRegularPremiumProcessed) {
		this.checkAnnualRegularPremiumProcessed = checkAnnualRegularPremiumProcessed;
	}

	public boolean isCheckAnnualRegularPremiumPlusProcessed() {
		return this.checkAnnualRegularPremiumPlusProcessed;
	}

	public void setCheckAnnualRegularPremiumPlusProcessed(
			boolean checkAnnualRegularPremiumPlusProcessed) {
		this.checkAnnualRegularPremiumPlusProcessed = checkAnnualRegularPremiumPlusProcessed;
	}

	public boolean isCheckAggAnnualRegularPremiumProcessed() {
		return this.checkAggAnnualRegularPremiumProcessed;
	}

	public void setCheckAggAnnualRegularPremiumProcessed(
			boolean checkAggAnnualRegularPremiumProcessed) {
		this.checkAggAnnualRegularPremiumProcessed = checkAggAnnualRegularPremiumProcessed;
	}

	public Rule9Obj(boolean checkLumpSumProcessed,
			java.util.List<java.lang.String> failReasonList,
			boolean checkAnnualRegularPremiumProcessed,
			boolean checkAnnualRegularPremiumPlusProcessed,
			boolean checkAggAnnualRegularPremiumProcessed,
			java.math.BigDecimal totalAnnualRegularPremium,
			java.util.List<com.axa.dm.autouw.Policy> targetPolicyList,
			java.util.List<com.axa.dm.autouw.Application> targetAppList) {
		this.checkLumpSumProcessed = checkLumpSumProcessed;
		this.failReasonList = failReasonList;
		this.checkAnnualRegularPremiumProcessed = checkAnnualRegularPremiumProcessed;
		this.checkAnnualRegularPremiumPlusProcessed = checkAnnualRegularPremiumPlusProcessed;
		this.checkAggAnnualRegularPremiumProcessed = checkAggAnnualRegularPremiumProcessed;
		this.totalAnnualRegularPremium = totalAnnualRegularPremium;
		this.targetPolicyList = targetPolicyList;
		this.targetAppList = targetAppList;
	}

}