package com.axa.dm.autouw;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule18Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("condition1Processed")
	private boolean condition1Processed;
	@org.kie.api.definition.type.Label("condition2Processed")
	private boolean condition2Processed;
	@org.kie.api.definition.type.Label("condition3Processed")
	private boolean condition3Processed;

	@org.kie.api.definition.type.Label("Max ECARE SI in USD")
	private java.math.BigDecimal maxEcareSiUsd;

	@org.kie.api.definition.type.Label("Income Multiplier")
	private java.math.BigDecimal incomeMultiplier;

	@org.kie.api.definition.type.Label(value = "Aggregate Daily Income")
	private java.math.BigDecimal aggDailyIncome;

	public Rule18Object() {
	}

	public boolean isCondition1Processed() {
		return this.condition1Processed;
	}

	public void setCondition1Processed(boolean condition1Processed) {
		this.condition1Processed = condition1Processed;
	}

	public boolean isCondition2Processed() {
		return this.condition2Processed;
	}

	public void setCondition2Processed(boolean condition2Processed) {
		this.condition2Processed = condition2Processed;
	}

	public boolean isCondition3Processed() {
		return this.condition3Processed;
	}

	public void setCondition3Processed(boolean condition3Processed) {
		this.condition3Processed = condition3Processed;
	}

	// public BigDecimal getLowerAmount(String occClass, BigDecimal target){
	// BigDecimal amt = new BigDecimal(0);
	// if(occClass.equals("1")){
	// amt = new BigDecimal(150000);
	// }else if(occClass.equals("2") || occClass.equals("3")){
	// amt = new BigDecimal(75000);
	// }

	// if(amt.compareTo(BigDecimal.ZERO) == 0) return -1;

	// if(amt.compareTo(target)==0){
	// return amt;
	// }else{
	// return target;
	// }

	// }

	public java.math.BigDecimal getMaxEcareSiUsd() {
		return this.maxEcareSiUsd;
	}

	public void setMaxEcareSiUsd(java.math.BigDecimal maxEcareSiUsd) {
		this.maxEcareSiUsd = maxEcareSiUsd;
	}

	public java.math.BigDecimal getIncomeMultiplier() {
		return this.incomeMultiplier;
	}

	public void setIncomeMultiplier(java.math.BigDecimal incomeMultiplier) {
		this.incomeMultiplier = incomeMultiplier;
	}

	public java.math.BigDecimal getAggDailyIncome() {
		return this.aggDailyIncome;
	}

	public void setAggDailyIncome(java.math.BigDecimal aggDailyIncome) {
		this.aggDailyIncome = aggDailyIncome;
	}

	public Rule18Object(boolean condition1Processed,
			boolean condition2Processed, boolean condition3Processed,
			java.math.BigDecimal maxEcareSiUsd,
			java.math.BigDecimal incomeMultiplier,
			java.math.BigDecimal aggDailyIncome) {
		this.condition1Processed = condition1Processed;
		this.condition2Processed = condition2Processed;
		this.condition3Processed = condition3Processed;
		this.maxEcareSiUsd = maxEcareSiUsd;
		this.incomeMultiplier = incomeMultiplier;
		this.aggDailyIncome = aggDailyIncome;
	}

}