package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rule19Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("rule19InsuredProcessed")
	private boolean rule19InsuredProcessed;

	@org.kie.api.definition.type.Label("rule19OwnerProcessed")
	private boolean rule19OwnerProcessed;

	@org.kie.api.definition.type.Label("applicationNoOwnerList")
	private java.util.List<java.lang.String> applicationNoOwnerList;

	@org.kie.api.definition.type.Label("applicationNoInsuredList")
	private java.util.List<java.lang.String> applicationNoInsuredList;

	@org.kie.api.definition.type.Label("applicationStatusOwnerList")
	private java.util.List<java.lang.String> applicationStatusOwnerList;

	@org.kie.api.definition.type.Label("applicationStatusInsuredList")
	private java.util.List<java.lang.String> applicationStatusInsuredList;

	@org.kie.api.definition.type.Label(value = "insuredName")
	private java.lang.String insuredName;

	@org.kie.api.definition.type.Label(value = "ownerName")
	private java.lang.String ownerName;

	public Rule19Object() {
	}

	public boolean isRule19InsuredProcessed() {
		return this.rule19InsuredProcessed;
	}

	public void setRule19InsuredProcessed(boolean rule19InsuredProcessed) {
		this.rule19InsuredProcessed = rule19InsuredProcessed;
	}

	public boolean isRule19OwnerProcessed() {
		return this.rule19OwnerProcessed;
	}

	public void setRule19OwnerProcessed(boolean rule19OwnerProcessed) {
		this.rule19OwnerProcessed = rule19OwnerProcessed;
	}

	public java.util.List<java.lang.String> getApplicationNoOwnerList() {
		return this.applicationNoOwnerList;
	}

	public void setApplicationNoOwnerList(
			java.util.List<java.lang.String> applicationNoOwnerList) {
		this.applicationNoOwnerList = applicationNoOwnerList;
	}

	public java.util.List<java.lang.String> getApplicationNoInsuredList() {
		return this.applicationNoInsuredList;
	}

	public void setApplicationNoInsuredList(
			java.util.List<java.lang.String> applicationNoInsuredList) {
		this.applicationNoInsuredList = applicationNoInsuredList;
	}

	public java.util.List<java.lang.String> getApplicationStatusOwnerList() {
		return this.applicationStatusOwnerList;
	}

	public void setApplicationStatusOwnerList(
			java.util.List<java.lang.String> applicationStatusOwnerList) {
		this.applicationStatusOwnerList = applicationStatusOwnerList;
	}

	public java.util.List<java.lang.String> getApplicationStatusInsuredList() {
		return this.applicationStatusInsuredList;
	}

	public void setApplicationStatusInsuredList(
			java.util.List<java.lang.String> applicationStatusInsuredList) {
		this.applicationStatusInsuredList = applicationStatusInsuredList;
	}

	public java.lang.String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(java.lang.String insuredName) {
		this.insuredName = insuredName;
	}

	public java.lang.String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(java.lang.String ownerName) {
		this.ownerName = ownerName;
	}

	public Rule19Object(boolean rule19InsuredProcessed,
			boolean rule19OwnerProcessed,
			java.util.List<java.lang.String> applicationNoOwnerList,
			java.util.List<java.lang.String> applicationNoInsuredList,
			java.util.List<java.lang.String> applicationStatusOwnerList,
			java.util.List<java.lang.String> applicationStatusInsuredList,
			java.lang.String insuredName, java.lang.String ownerName) {
		this.rule19InsuredProcessed = rule19InsuredProcessed;
		this.rule19OwnerProcessed = rule19OwnerProcessed;
		this.applicationNoOwnerList = applicationNoOwnerList;
		this.applicationNoInsuredList = applicationNoInsuredList;
		this.applicationStatusOwnerList = applicationStatusOwnerList;
		this.applicationStatusInsuredList = applicationStatusInsuredList;
		this.insuredName = insuredName;
		this.ownerName = ownerName;
	}

}