package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SpecialField implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "value")
	private java.lang.String value;

	public SpecialField() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public SpecialField(java.lang.String description, java.lang.String value) {
		this.description = description;
		this.value = value;
	}

}