package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SpecialCase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label("Policy No")
	private java.lang.String policyNo;
	@org.kie.api.definition.type.Label("Special Code")
	private java.lang.String specialCode;
	@org.kie.api.definition.type.Label("Special Case Type")
	private java.lang.String specialCaseType;

	public SpecialCase() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getSpecialCode() {
		return this.specialCode;
	}

	public void setSpecialCode(java.lang.String specialCode) {
		this.specialCode = specialCode;
	}

	public java.lang.String getSpecialCaseType() {
		return this.specialCaseType;
	}

	public void setSpecialCaseType(java.lang.String specialCaseType) {
		this.specialCaseType = specialCaseType;
	}

	public SpecialCase(java.lang.String role, java.lang.String policyNo,
			java.lang.String specialCode, java.lang.String specialCaseType) {
		this.role = role;
		this.policyNo = policyNo;
		this.specialCode = specialCode;
		this.specialCaseType = specialCaseType;
	}

}