package com.axa.dm.autouw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StandardRateObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Plan Code")
	private java.lang.String planCode;
	@org.kie.api.definition.type.Label("Class Code")
	private java.lang.String classCode;

	@org.kie.api.definition.type.Label(value = "Total no of objects")
	private int totalCount;

	public StandardRateObject() {
	}

	public java.lang.String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(java.lang.String planCode) {
		this.planCode = planCode;
	}

	public java.lang.String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(java.lang.String classCode) {
		this.classCode = classCode;
	}

	public int getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(int totalCount) {
		this.totalCount = totalCount;
	}

	public StandardRateObject(java.lang.String planCode,
			java.lang.String classCode, int totalCount) {
		this.planCode = planCode;
		this.classCode = classCode;
		this.totalCount = totalCount;
	}

}