package com.axa.dm.autouw;

import java.lang.Number;

rule "Rule_10_ownerAsPayor"
	dialect "mvel"
	when
		not (Payor()) 
		Owner( $ownerId : id, $ownerFullName : fullName, $ownerDob : dob, $ownerAnnualIncome : annualIncome != null , $ownerOccupationClass : occupationClass, $ownerAnnualExpense : annualExpense, $ownerAnnualIncomeEcna : annualIncomeEcna, $ownerAnnualDisposableIncome : annualDisposableIncome, $ownerOccupationName : occupationName)
		exists (Insured( id != $ownerId ) or Insured( dob != $ownerDob ) or Insured( !fullName.equalsIgnoreCase($ownerFullName)) ) 
	then
		Payor fact0 = new Payor();
		fact0.setAnnualIncome( $ownerAnnualIncome );
		fact0.setOccupationClass( $ownerOccupationClass );
		fact0.setRole(Constants.ownerPayorId);
		fact0.setAnnualExpense($ownerAnnualExpense);
		fact0.setAnnualIncomeEcna($ownerAnnualIncomeEcna);
		fact0.setAnnualDisposableIncome($ownerAnnualDisposableIncome);
		fact0.setOccupation($ownerOccupationName);
		insert( fact0 );
end
