package com.axa.dm.autouw;

import java.lang.Number;

rule "Rule_5"
	dialect "java"
	when
		$processObj : ProcessObject( rule5Processed == false )
		Insured( $fullName : fullName != null, $gender : gender != null, $id : id != null, $dob : dob != null)
		CurrentApplication( $insuredToOwner : insuredtoOwner != null, $formId : formId)
		Owner( fullName != $fullName || gender != $gender || id != $id || dob != $dob )
		( CurrentApplication( insuredtoOwner == "Other" ) or Insured( age >= 18 && $insuredToOwner.toLowerCase() == "parent" ) or Insured( age < 18 && $insuredToOwner.toLowerCase() != "parent" ) or Beneficiary( beneficiaryRelationship.toLowerCase() == "other" ) )
	    $resultObj : Result( $individualResultList : individualResult)
		$ruleObj : RuleObject( ruleNo == "5" )
	then
		$processObj.setRule5Processed( true );
		List failedReasons = new ArrayList<String>();
		failedReasons.add("Proposed Owner or Beneficiary does not have insurable interest on the Proposed Insured. ");
		
		
		IndividualResult $individualResult = new IndividualResult();
		
		InsuredIndividual $insuredIndividual = new InsuredIndividual();
		$insuredIndividual.setFailedReasons(failedReasons);
		$insuredIndividual.setDecision("Fail");
		
		$individualResult.setRuleNo($ruleObj.getRuleNo());
        $individualResult.setDecision("Fail");
        $individualResult.setRuleName($ruleObj.getRuleName());
        $individualResult.setMessageToClientEng($ruleObj.getMessageToClientEng());
        $individualResult.setMessageToClientChi($ruleObj.getMessageToClientChi());
        $individualResult.setInsuredIndividual($insuredIndividual);
        $individualResultList.add( $individualResult );
        
        update($processObj);
        long dateDiff = new Date().getTime() - $processObj.getStartTime().getTime();
        Utils.loggingTime($ruleObj.getRuleNo(),dateDiff);
        Utils.loggingDebug("Form ID: "+$formId + " | " + $individualResult.toJson());
end
