package com.axa.dm.autouw;

import java.lang.Number;

rule "Rule_34_init_object"
    dialect "java"
    when
        not (Rule34Object())
    then
        Rule34Object rule34Obj = new Rule34Object();
        rule34Obj.setPlanList(new ArrayList());
        insert(rule34Obj);
    end

rule "Rule_34_extract_plan_code"
    no-loop true
    dialect "java"
    when
        $rule34Obj : Rule34Object(rule34ExtractedProcessed == false, $planList : planList)
        $processObj : ProcessObject( rule34Processed == false )
		Basic ( productType != null, isValidProduct("ECARE"),$planCode: planCode)
       // Product( productType in ( "ECARE" ) , $validPlanCode : planCode)
        //Basic( $planCode: planCode == $validPlanCode)
    then
        $planList.add($planCode);
        $rule34Obj.setRule34ExtractedProcessed(true);
        update($rule34Obj);
    end
        

rule "Rule_34"
    dialect "java"
    when
        $rule34Obj : Rule34Object(rule34ExtractedProcessed == true, $planList : planList)
        $processObj : ProcessObject( rule34Processed == false )
        $resultObj : Result( $individualResultList : individualResult)
        $ruleObj : RuleObject( ruleNo == "34" )
        CurrentApplication ($formId : formId)
    then
        $processObj.setRule34Processed( true );
        List failedReasons = new ArrayList<String>();
        
        for (int i=0;i < $planList.size();i++){
          failedReasons.add("Plan " + $planList.get(i) + " fall into exclusion list of auto-UW");
        }
        
        IndividualResult $individualResult = new IndividualResult();
        
        InsuredIndividual $insuredIndividual = new InsuredIndividual();
        $insuredIndividual.setFailedReasons(failedReasons);
        $insuredIndividual.setDecision("Fail");
        
        $individualResult.setRuleNo($ruleObj.getRuleNo());
        $individualResult.setDecision("Fail");
        $individualResult.setRuleName($ruleObj.getRuleName());
        $individualResult.setMessageToClientEng($ruleObj.getMessageToClientEng());
        $individualResult.setMessageToClientChi($ruleObj.getMessageToClientChi());
        $individualResult.setInsuredIndividual($insuredIndividual);
        $individualResultList.add( $individualResult );
        update($processObj);
        
        long dateDiff = new Date().getTime() - $processObj.getStartTime().getTime();
        Utils.loggingTime($ruleObj.getRuleNo(),dateDiff);
        Utils.loggingDebug("Form ID: "+$formId + " | " + $individualResult.toJson());
end
