package com.axa.dm.autouw;

import java.lang.Number;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

rule "Rule_12A"
          dialect "java"
          when
                CurrentApplication ($formId : formId, $riderList : rider)
                   $processObj : ProcessObject( rule12AProcessed == false, $policyList : policy, $applicationList: application, $policyRiderList : policyRider, $appRiderList : applicationRider )
                   $insured : Insured( $maxLifeSumInsured : maxLifeSumInsuredUsd != null )
                   ExchangeRateObject( fromCurrency == "HKD", toCurrency == "USD", $exchangeRate : exchangeRate)
                   
                   exists( 
                        Basic( productType != null, isValidProduct("MAXX","SJVCS","FGS","FGS 2","WA") ) or 
                        Rider( productType != null, isValidProduct("MAXX","SJVCS","FGS","FGS 2","WA") ) 
                    )
                    
                     //************ Current Application *****************
                   $totalBasicSumInsured : Number( ) from accumulate ( Basic( $basicSumInsured : sumInsuredHkd != null,productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")),
                             sum($basicSumInsured.multiply($exchangeRate))) // current application with GIO basic
                
                    Number ($riderCount : intValue()) from accumulate (
                        Rider() from $riderList,count(1)
                    )
                    
                    Number (intValue() == $riderCount) from accumulate(
                        Rider(sumInsuredHkd != null,
                                productType != null),
                        count(1)
                    )
                   $totalRiderSumInsured : (Number( ) from accumulate ( 
                            Rider( $riderSumInsured : sumInsuredHkd != null,
                                productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            ),
                            sum($riderSumInsured.multiply($exchangeRate)) // current application with GIO rider
                        )
                    )
                    
                    //**************************************************
                    
                    //****************** Policy **********************
                    
                    Number ($policyCount : intValue()) from accumulate(
                        Policy() from $policyList, count(1)
                    )
                    
                    Number (intValue() == $policyCount) from accumulate(
                        Policy(sumInsuredHkd != null, productType != null),count(1)
                    )
                    
                   $totalPolicySumInsured : Number( ) from accumulate ( 
                            Policy( $policySumInsured : sumInsuredHkd != null, 
                                    Constants.insured.equals(currentRole), 
                                    Constants.insured.equals(role), isInforce(policyStatus) == true,
                                    productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            ),
                             sum($policySumInsured.multiply($exchangeRate)) // all in-force GIO Basic
                    ) 
                    
                    Number ($policyRiderCount : intValue()) from accumulate(
                        PolicyRider() from $policyRiderList, count(1)
                    )
                    
                    Number (intValue() == $policyRiderCount) from accumulate(
                        PolicyRider(sumInsuredHkd != null, productType != null),count(1)
                    )
                             
                   $totalPolicyRiderSumInsured : Number( ) from accumulate ( 
                            PolicyRider( $policyRiderSumInsured : sumInsuredHkd != null, Constants.insured.equals(currentRole), Constants.insured.equals(role), "".equals(riderStatus.trim()),
                                productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            ),
                             sum($policyRiderSumInsured.multiply($exchangeRate)) // selected in-force GIO Policy Rider
                    ) 
                             
                    //************************************************ 
                      
                    //***************** Application ******************** 
                    
                    Number ($appCount : intValue()) from accumulate(
                        Application() from $applicationList, count(1)
                    )
                    
                    Number (intValue() == $appCount) from accumulate(
                        Application(sumInsuredHkd != null, productType != null),count(1)
                    )
                    
                    $totalApplicationSumInsured : Number( ) from accumulate ( 
                            Application( $applicationSumInsured : sumInsuredHkd != null, 
                                        Constants.insured.equals(currentRole), 
                                        Constants.insured.equals(role), 
                                        isActive(applicationStatus),
                                        productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            ),
                             sum($applicationSumInsured.multiply($exchangeRate)) // all active GIO application
                    )
                    
                    Number ($appRiderCount : intValue()) from accumulate(
                        ApplicationRider() from $appRiderList, count(1)
                    )
                    
                    Number (intValue() == $appRiderCount) from accumulate(
                        ApplicationRider(sumInsuredHkd != null, productType != null),count(1)
                    )
                    
                     $totalApplicationRiderSumInsured : Number( ) from accumulate ( 
                            ApplicationRider( $applicationRiderSumInsured : sumInsuredHkd != null, Constants.insured.equals(currentRole), Constants.insured.equals(role),isActive(applicationStatus),
                                productType != null, isValidProduct("MAXX","SJVCS","FGS","FGSII","WA") 
                            ),
                             sum($applicationRiderSumInsured.multiply($exchangeRate)) // all active GIO application rider
                    )

                    
                    //**************************************************
                    
                   eval ( 
                       new BigDecimal($totalPolicySumInsured.toString()).add(
                       new BigDecimal($totalPolicyRiderSumInsured.toString())).add(
                       new BigDecimal($totalApplicationSumInsured.toString())).add(
                       new BigDecimal($totalApplicationRiderSumInsured.toString())).add(
                       new BigDecimal($totalBasicSumInsured.toString())).add(
                       new BigDecimal($totalRiderSumInsured.toString())).compareTo($maxLifeSumInsured) == 1 
                    )
                   $resultObj : Result( $individualResultList : individualResult)
                   $ruleObj : RuleObject( ruleNo == "12A" )
          then
                   $processObj.setRule12AProcessed( true );
                   BigDecimal $totalSi = new BigDecimal($totalPolicySumInsured.toString()).add(
                       new BigDecimal($totalPolicyRiderSumInsured.toString())).add(
                       new BigDecimal($totalApplicationSumInsured.toString())).add(
                       new BigDecimal($totalApplicationRiderSumInsured.toString())).add(
                       new BigDecimal($totalBasicSumInsured.toString())).add(
                       new BigDecimal($totalRiderSumInsured.toString()));
                   IndividualResult $individualResult = new IndividualResult();
                   InsuredIndividual $insuredIndividual = new InsuredIndividual();
                //   OwnerIndividual $ownerIndividual = new OwnerIndividual();
                   java.text.DecimalFormat df = new java.text.DecimalFormat(Constants.decimalFormatString);
                   List failedReasons = new ArrayList<String>();
                   List otherDetails = new ArrayList<OtherDetailObj>();
                   List gioList = new ArrayList<String>();
                   gioList.add("MAXX");
                   gioList.add("SJVCS");
                   gioList.add("FGS");
                   gioList.add("FGSII");
                   gioList.add("WA");
                   
                   int increment = 0;
                   
                   OtherDetailObj occupation = new OtherDetailObj();
                   occupation.setName("Occupation");
                   occupation.setValue($insured.getOccupationDesc());
                   otherDetails.add(occupation);
                   
                   OtherDetailObj occupationClass = new OtherDetailObj();
                   occupationClass.setName("Occupation Class");
                   occupationClass.setValue($insured.getOccupationClass());
                   otherDetails.add(occupationClass);
                   
                   OtherDetailObj resident = new OtherDetailObj();
                   resident.setName("Resident");
                   resident.setValue($insured.getCountryofResidency());
                   otherDetails.add(resident);
                   
                   OtherDetailObj totalSiObj = new OtherDetailObj();
                   totalSiObj.setName("Total SI");
                   totalSiObj.setValue(df.format($totalSi));
                   otherDetails.add(totalSiObj);
                   
                   OtherDetailObj prePolicy = new OtherDetailObj();
                   prePolicy.setName("Previous Policy");
                   prePolicy.setValue("");
                   otherDetails.add(prePolicy);
                   
                   increment = 0;
                   
                   if ($policyList != null){
                   for (int i=0;i < $policyList.size();i++){
                       OtherDetailObj policy = new OtherDetailObj();
                       Policy tempPolicy = (Policy) $policyList.get(i);
                       if (
                        tempPolicy.isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                        && Constants.insured.equals(tempPolicy.getCurrentRole())
                        && Constants.insured.equals(tempPolicy.getRole())
                        && tempPolicy.isInforce(tempPolicy.getPolicyStatus())
                       ){
                            increment++;
                            policy.setName("(" + increment + ")");
                            policy.setValue(tempPolicy.getPolicyNo() + ";" + tempPolicy.getProductSeriesConcat() + ";" + tempPolicy.getCurrency() + df.format(tempPolicy.getSumInsured()));
                            otherDetails.add(policy);
                       }
                        
                   }
                   }
                   
                   if ($policyRiderList != null){
                   for (int i=0;i < $policyRiderList.size();i++){
                       OtherDetailObj policyRider = new OtherDetailObj();
                       PolicyRider tempPolicyRider = (PolicyRider) $policyRiderList.get(i);
                       if (tempPolicyRider.isValidProduct("MAXX","SJVCS","FGS","FGSII","WA") 
                        && Constants.insured.equals(tempPolicyRider.getCurrentRole())
                        && Constants.insured.equals(tempPolicyRider.getRole())
                        && "".equals(tempPolicyRider.getRiderStatus())
                       ){
                            increment++;
                            policyRider.setName("(" + increment + ")");
                            policyRider.setValue(tempPolicyRider.getPolicyNo() + ";" + tempPolicyRider.getProductSeriesConcat() + ";" + tempPolicyRider.getCurrency() + df.format(tempPolicyRider.getSumInsured()));
                            otherDetails.add(tempPolicyRider);
                       }
                        
                   }
                   }
                   
                   OtherDetailObj preApp = new OtherDetailObj();
                   preApp.setName("Previous Application");
                   preApp.setValue("");
                   otherDetails.add(preApp);
                   
                   increment = 0;
                   
                   if ($applicationList != null){
                   for (int i=0;i < $applicationList.size();i++){
                       OtherDetailObj app = new OtherDetailObj();
                       Application tempApp = (Application) $applicationList.get(i);
                       if (
                            tempApp.isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            && Constants.insured.equals(tempApp.getCurrentRole())
                            && Constants.insured.equals(tempApp.getRole())
                            && tempApp.isActive(tempApp.getApplicationStatus())
                        ){
                            increment++;
                            app.setName("(" + increment + ")");
                            app.setValue(tempApp.getApplicationNo() + ";" + tempApp.getProductSeriesConcat() + ";" + tempApp.getCurrency() + df.format(tempApp.getSumInsured()));
                            otherDetails.add(app);
                       }
                        
                   }
                   }
                   
                   if ($appRiderList != null){
                   for (int i=0;i < $appRiderList.size();i++){
                       OtherDetailObj appRider = new OtherDetailObj();
                       ApplicationRider tempAppRider = (ApplicationRider) $appRiderList.get(i);
                       if (
                            tempAppRider.isValidProduct("MAXX","SJVCS","FGS","FGSII","WA")
                            && Constants.insured.equals(tempAppRider.getCurrentRole())
                            && Constants.insured.equals(tempAppRider.getRole())
                            && tempAppRider.isActive(tempAppRider.getApplicationStatus())
                        ){
                            increment++;
                            appRider.setName("(" + increment + ")");
                            appRider.setValue(tempAppRider.getApplicationNo() + ";" + tempAppRider.getProductSeriesConcat() + ";" + tempAppRider.getCurrency() + df.format(tempAppRider.getSumInsured()));
                            otherDetails.add(appRider);
                       }
                        
                   }
                   }
                   
                   failedReasons.add( "Maximum Sum Insured limit (for Life Sum Insured) GIO Validation" );
                   
                   // ******* Prepare InsuredIndividual *********
                   $insuredIndividual.setFailedReasons(failedReasons);
                   $insuredIndividual.setDecision(Constants.failDecision);
                   $insuredIndividual.setOtherDetails(otherDetails);
                   
                   // *******************************************
                //   $ownerIndividual.setDecision(Constants.failDecision);
                   
                   $individualResult.setRuleNo($ruleObj.getRuleNo());
                   $individualResult.setDecision(Constants.failDecision);
                   $individualResult.setRuleName($ruleObj.getRuleName());
                   $individualResult.setMessageToClientEng($ruleObj.getMessageToClientEng());
                   $individualResult.setMessageToClientChi($ruleObj.getMessageToClientChi());
                   $individualResult.setInsuredIndividual($insuredIndividual);
                //   $individualResult.setOwnerIndividual($ownerIndividual);
                   $individualResultList.add( $individualResult );
                   update($processObj);
                   long dateDiff = new Date().getTime() - $processObj.getStartTime().getTime();
                   Utils.loggingTime($ruleObj.getRuleNo(),dateDiff);
                   Utils.loggingDebug("Form ID: "+$formId + " | " + $individualResult.toJson());
end
