package com.axa.dm.autouw;

import java.lang.Number;
import java.util.Date;

rule "Rule_3_Insured"
	dialect "java"
	when
		$processObject : ProcessObject( rule3InsuredProcessed == false )
		
		exists($insured : Insured( countryofPermanentAddress.toLowerCase() not in ( "hong kong", "macau", "china" ) || countryofResidency.toLowerCase() not in ( "hong Kong", "macau", "china" ) || countryofResidency6Months.toLowerCase() not in ( "hong kong", "macau", "china" ) || nationality.toLowerCase() not in ( "hong kong", "macau", "china" ) ))
		$resultObj : Result( $individualResultList : individualResult)
	    $ruleObj : RuleObject( ruleNo == "3" )
	    $individualResult: IndividualResult( ruleNo == "3" )
	then
		List failedReasons = new ArrayList<String>();
		failedReasons.add("Proposed Insured is a foreigner.");
		InsuredIndividual $insuredIndividual = new InsuredIndividual();
		$insuredIndividual.setFailedReasons(failedReasons);
		$insuredIndividual.setDecision("Fail");
        $individualResult.setInsuredIndividual($insuredIndividual);
        
        
        update($individualResult);
        $processObject.setRule3InsuredProcessed(true);
        update($processObject);
end

rule "Rule_3_Owner"
	dialect "java"
	when
		$processObject : ProcessObject( rule3OwnerProcessed == false )
		
		exists($owner : Owner( countryofPermanentAddress.toLowerCase() not in ( "hong kong", "macau", "china" ) || countryofResidency.toLowerCase() not in ( "hong kong", "macau", "china" ) || countryofResidency6Months.toLowerCase() not in ( "hong kong", "macau", "china" ) || nationality.toLowerCase() not in ( "hong kong", "macau", "china" ) )
		)
		$resultObj : Result( $individualResultList : individualResult)
	    $ruleObj : RuleObject( ruleNo == "3" )
	    $individualResult: IndividualResult( ruleNo == "3" )
	then
		List failedReasons = new ArrayList<String>();
		failedReasons.add("Proposed Owner is a foreigner.");
		OwnerIndividual $ownerIndividual = new OwnerIndividual();
		$ownerIndividual.setFailedReasons(failedReasons);
		$ownerIndividual.setDecision("Fail");
        $individualResult.setOwnerIndividual($ownerIndividual);
    
        update($individualResult);
        $processObject.setRule3OwnerProcessed(true);
        update($processObject);
end

rule "Rule_3 final"
    dialect "java"
    when
        $processObj : ProcessObject( (rule3InsuredProcessed == true || rule3OwnerProcessed == true) , rule3FinalProcessed == false )
        $individualResult : IndividualResult(ruleNo == "3")
        $ruleObj : RuleObject( ruleNo == "3" )
        Result( $individualResultList : individualResult)
        CurrentApplication ($formId : formId)
    then
    
		$individualResult.setRuleNo($ruleObj.getRuleNo());
        $individualResult.setDecision("Fail");
        $individualResult.setRuleName($ruleObj.getRuleName());
        $individualResult.setMessageToClientEng($ruleObj.getMessageToClientEng());
        $individualResult.setMessageToClientChi($ruleObj.getMessageToClientChi());
        
        $individualResultList.add($individualResult);
        $processObj.setRule3FinalProcessed(true);
        update($processObj);
        long dateDiff = new Date().getTime() - $processObj.getStartTime().getTime();
        Utils.loggingTime($ruleObj.getRuleNo(),dateDiff);
        Utils.loggingDebug("Form ID: "+$formId + " | " + $individualResult.toJson());
    end