package com.axa.dm.autouw;

rule "Rule_38"
    dialect "java"
    when 
        $processObj : ProcessObject( rule38Processed == false)
        exists(Owner(nationalHoldingFlag != null, nationalHoldingFlag == true))
        $ruleObj : RuleObject( ruleNo == "38" )
        $resultObj : Result( $individualResultList : individualResult)
        CurrentApplication ($formId : formId)
    then
        $processObj.setRule38Processed(true);
        List failedReasons = new ArrayList<String>();
        List failedApplicationNo = new ArrayList<String>();
        failedReasons.add("Proposed Owner's employed company is of national holding or its business nature is casino.");
    
        IndividualResult $individualResult = new IndividualResult();
        
        OwnerIndividual $ownerIndividual = new OwnerIndividual();
        $individualResult.setOwnerIndividual($ownerIndividual);
        
        InsuredIndividual $insuredIndividual = new InsuredIndividual();
        $ownerIndividual.setFailedReasons(failedReasons);
        $ownerIndividual.setDecision("Fail");
        
        $individualResult.setRuleNo($ruleObj.getRuleNo());
        $individualResult.setDecision("Fail");
        $individualResult.setRuleName($ruleObj.getRuleName());
        $individualResult.setMessageToClientEng($ruleObj.getMessageToClientEng());
        $individualResult.setMessageToClientChi($ruleObj.getMessageToClientChi());
        $individualResult.setOwnerIndividual($ownerIndividual);
        $individualResultList.add( $individualResult );
        update($processObj);
        long dateDiff = new Date().getTime() - $processObj.getStartTime().getTime();
        Utils.loggingTime($ruleObj.getRuleNo(),dateDiff);
        Utils.loggingDebug("Form ID: "+$formId + " | " + $individualResult.toJson());
end